const FILTER = [
    // 'AAPL'
    //# 'XERS', 'PLTR', 'PRCH', 'RKLB', 'OKLO', 'SOFI', 'CRDO', 'HOOD', 'KOPN', 'SHOP',
    'XERS', 'CIFR', 'PLTR', /*PRCH',*/ 'RKLB', 'OKLO', 'SOFI', 'CRDO', 'HOOD', 'ABCL',
    // TMC', 'LEU','ABCL','SNDK','CIFR', 
];
const TOPS =
// {
//     '2025-11-24': ['ZJK', 'CGEM', 'ZYXI', 'BLFY', 'ENLV', 'PACB', 'TYRA', 'INV', 'ADPT', 'LYEL', 'JYD', 'RLAY', 'QDEL', 'TXG', 'GRAL', 'WALD', 'TNGX', 'SEPN', 'BCAX', 'OLMA', 'AZTA', 'PSNL', 'GRI', 'JACK', 'LPRO'], 
//     '2025-11-25': ['ZJK', 'INV', 'BLFY', 'ZYXI', 'PACB', 'JYD', 'CGEM', 'SYM', 'ENLV', 'PSNL', 'TLSI', 'JACK', 'QDEL', 'TYRA', 'ADPT', 'SPRY', 'FOSL', 'SMX', 'HCAT', 'ESPR', 'LYEL', 'CSTE', 'CRMT', 'TITN', 'NNOX'],
//     '2025-11-26': ['SMX', 'ZYXI', 'AMBR', 'ZJK', 'QNTM', 'SYM', 'CSTE', 'BLFY', 'INV', 'ARWR', 'KALA', 'CGEM', 'LYEL', 'TLSI', 'ESPR', 'IBG', 'HCAT', 'OLMA', 'CTXR', 'SPRY', 'FOSL', 'JYD', 'JACK', 'PACB', 'TYRA'],
//     '2025-11-27': ['SMX', 'ZYXI', 'AMBR', 'ZJK', 'QNTM', 'SYM', 'CSTE', 'BLFY', 'INV', 'ARWR', 'KALA', 'CGEM', 'LYEL', 'TLSI', 'ESPR', 'IBG', 'HCAT', 'OLMA', 'CTXR', 'SPRY', 'FOSL', 'JYD', 'JACK', 'PACB', 'TYRA'],
// }
// {
//     '2025-11-24': ['ZJK','CGEM','ZYXI','BLFY','ENLV','PACB','TYRA','INV','ADPT','LYEL','JYD','RLAY','QDEL','TXG','GRAL','WALD','TNGX','SEPN','BCAX','OLMA','AZTA','PSNL','GRI','JACK','LPRO'],
//     '2025-11-25': ['ZJK','INV','BLFY','ZYXI','PACB','JYD','CGEM','SYM','ENLV','PSNL','TLSI','JACK','QDEL','TYRA','ADPT','SPRY','FOSL','SMX','HCAT','ESPR','LYEL','CSTE','CRMT','TITN','NNOX'],
//     '2025-11-26': ['SMX','ZYXI','AMBR','ZJK','QNTM','SYM','CSTE','BLFY','INV','ARWR','KALA','CGEM','LYEL','TLSI','ESPR','IBG','HCAT','OLMA','CTXR','SPRY','FOSL','JYD','JACK','PACB','TYRA'],
//     '2025-11-27': ['SMX','ZYXI','AMBR','ZJK','QNTM','SYM','CSTE','BLFY','INV','ARWR','KALA','CGEM','LYEL','TLSI','ESPR','IBG','HCAT','OLMA','CTXR','SPRY','FOSL','JYD','JACK','PACB','TYRA'],
// }
// {
//     "2025-11-14": ['MRSN', 'SRDX', 'GTBP', 'RLMD', 'ENGN', 'TXMD', 'ALTO', 'GORV', 'IMOS', 'RPID', 'EWTX', 'IRWD', 'PUBM', 'SRRK', 'PRLD', 'AVDL', 'REAL', 'TRDA', 'SEPN', 'MRVI', 'ATEX', 'KALV', 'ELVN', 'CNTA', 'UK'],
//     "2025-11-15": ['MRSN', 'TXMD', 'GTBP', 'SONN', 'RLMD', 'IMOS', 'UK', 'RPID', 'SRRK', 'CMBM', 'IRWD', 'SEPN', 'ALTO', 'AVDL', 'EWTX', 'ATEX', 'ONDS', 'RIGL', 'CNTA', 'CELC', 'BCAB', 'HROW', 'QRHC', 'STOK', 'OMER"'],
//     "2025-11-16": ['MRSN', 'GTBP', 'SONN', 'CMBM', 'AVDL', 'IMOS', 'ATEX', 'CNTA', 'UK', 'SRRK', 'TXMD', 'SEPN', 'ONDS', 'RLMD', 'KALV', 'CLBT', 'CELC', 'BCAB', 'OMER', 'DNTH', 'SMTK', 'CTKB', 'QTRX', 'TRDA', 'MRVI'],
//     "2025-11-17": ['BCAB', 'SSP', 'SGML', 'OMER', 'ZYME', 'JBIO', 'RPTX', 'DRIO', 'CDZI', 'JAZZ', 'TERN', 'ALXO', 'UK', 'AVDL', 'SRRK', 'SONN', 'ANNX', 'FULC', 'ALGS', 'QRHC', 'AMLX', 'CTKB', 'AIRG', 'KALV', 'NUVL'],
//     "2025-11-18": ['OLMA', 'BCAB', 'SSP', 'CDZI', 'SGML', 'TERN', 'KLRS', 'JAZZ', 'RPTX', 'ONDS', 'SRRK', 'ALGS', 'JBIO', 'ALXO', 'NAUT', 'ARVN', 'WALD', 'OMER', 'ALMS', 'ZYME', 'ANNX', 'UK', 'VNDA', 'AVDL', 'DRIO'],
//     "2025-11-19": ['OLMA', 'SGML', 'BCAB', 'ANNX', 'SSP', 'NAUT', 'FULC', 'KLRS', 'ALGS', 'CDZI', 'TERN', 'SRRK', 'JAZZ', 'WALD', 'EXAS', 'ALMS', 'DRIO', 'JBIO', 'RPTX', 'ONDS', 'ZYME', 'AVDL', 'UK', 'OMER', 'DMAC'],
//     "2025-11-20": ['SQQQ', 'OLMA', 'SGML', 'BCAB', 'ANNX', 'EXAS', 'AIRG', 'ALMS', 'DRIO', 'ALGS', 'TYRA', 'NFE', 'KLRS', 'WALD', 'ZYME', 'SSP', 'CLLS', 'CRNC', 'DMAC', 'TXMD', 'GRI', 'FULC', 'TERN', 'RPTX', 'CRVO'],
//     "2025-11-21": ['SQQQ', 'OLMA', 'WALD', 'ANNX', 'EXAS', 'NNOX', 'PACB', 'ALGS', 'TYRA', 'ADPT', 'ALMS', 'CRNC', 'NRIX', 'PSNL', 'FULC', 'ZYXI', 'DMAC', 'KLRS', 'FOSL', 'QCLS', 'ZJK', 'SGML', 'NAUT', 'JYD', 'TNGX'],
//     "2025-11-22": ['SQQQ', 'EXAS', 'WALD', 'NNOX', 'ANNX', 'PACB', 'ZYXI', 'CRNC', 'TYRA', 'ADPT', 'QCLS', 'SGML', 'FOSL', 'NRIX', 'ZJK', 'ALGS', 'PSNL', 'TNGX', 'JYD', 'GRI', 'KLRS', 'REFR', 'LQDT', 'ALMS', 'OABI'],
//     "2025-11-23": ['SQQQ', 'EXAS', 'ZYXI', 'WALD', 'CRNC', 'PACB', 'ADPT', 'TYRA', 'ZJK', 'NNOX', 'NRIX', 'FOSL', 'JYD', 'FEMY', 'PSNL', 'TNGX', 'LQDT', 'ANNX', 'QCLS', 'QTRX', 'AZTA', 'TXG', 'TXMD', 'LOBO', 'INV'],
//     "2025-11-24": ['ZJK', 'CGEM', 'ZYXI', 'BLFY', 'ENLV', 'PACB', 'TYRA', 'INV', 'ADPT', 'LYEL', 'JYD', 'RLAY', 'QDEL', 'TXG', 'GRAL', 'WALD', 'TNGX', 'SEPN', 'BCAX', 'OLMA', 'AZTA', 'PSNL', 'GRI', 'JACK', 'LPRO'],
//     "2025-11-25": ['ZJK', 'INV', 'BLFY', 'ZYXI', 'PACB', 'JYD', 'CGEM', 'SYM', 'ENLV', 'PSNL', 'TLSI', 'JACK', 'QDEL', 'TYRA', 'ADPT', 'SPRY', 'FOSL', 'SMX', 'HCAT', 'ESPR', 'LYEL', 'CSTE', 'CRMT', 'TITN', 'NNOX'],
//     "2025-11-26": ['SMX', 'ZYXI', 'AMBR', 'ZJK', 'QNTM', 'SYM', 'CSTE', 'BLFY', 'INV', 'ARWR', 'KALA', 'CGEM', 'LYEL', 'TLSI', 'ESPR', 'IBG', 'HCAT', 'OLMA', 'CTXR', 'SPRY', 'FOSL', 'JYD', 'JACK', 'PACB', 'TYRA'],
//     "2025-11-27": ['SMX', 'ZYXI', 'AMBR', 'ZJK', 'QNTM', 'SYM', 'CSTE', 'BLFY', 'INV', 'ARWR', 'KALA', 'CGEM', 'LYEL', 'TLSI', 'ESPR', 'IBG', 'HCAT', 'OLMA', 'CTXR', 'SPRY', 'FOSL', 'JYD', 'JACK', 'PACB', 'TYRA'],
// }
{
    // "2025-04-30": ["JBIO", "RCKY", "ODD", "BRNS", "CGON", "ATON", "KNSA", "LFMD", "EVLV", "HSAI", "KALA", "SBET", "FMST", "IBIO", "CECO", "HTOO", "ABEO", "FRGT", "WING", "SNBR", "ECX", "TVTX", "GRWG", "CTOR", "MRSN"],
    // "2025-05-01": ["JBIO", "ETHZ", "FMST", "ODD", "CGON", "TRVG", "RCKY", "RNAZ", "DRCT", "KNSA", "BRNS", "LOT", "AIFU", "SBET", "ABEO", "LFMD", "COGT", "CECO", "NTGR", "FULC", "TXMD", "SNBR", "FNGR", "MBX", "MYRG"],
    // "2025-05-02": ["HSDT", "JBIO", "FRGT", "FULC", "RYM", "PONY", "BIVI", "RCKY", "LOT", "ODD", "FMST", "ETHZ", "TRVG", "DRCT", "FNGR", "RNAZ", "APYX", "CTOR", "KPTI", "VNET", "MBX", "KNSA", "CECO", "BCAB", "FTDR"],
    // "2025-05-03": ["HSDT", "FRGT", "FULC", "RYM", "RCKY", "BIVI", "ETHZ", "ODD", "APYX", "FNGR", "LOT", "DRCT", "CDLX", "BCAB", "TRVG", "CTOR", "FTDR", "ADPT", "MYRG", "MBX", "STRO", "DUOL", "VNET", "TTMI", "FMST"],
    // "2025-05-04": ["HSDT", "FRGT", "RYM", "FULC", "ETHZ", "FNGR", "BIVI", "SMCX", "APYX", "RLMD", "ADPT", "LOT", "CDLX", "DUOL", "AIFU", "ASTL", "TNDM", "COMM", "GHRS", "STRO", "TRVG", "FTDR", "FWRD", "MYRG", "TTMI"],
    // "2025-05-05": ["HSDT", "FRGT", "GDEV", "SBET", "RYM", "CDLX", "FULC", "ABTC", "FNGR", "BIVI", "ADPT", "QNTM", "CTMX", "DRCT", "IRTC", "ETHZ", "BCRX", "DUOL", "SSP", "PRDO", "ZYXI", "JBIO", "TRUP", "ARVN", "CART"],
    // "2025-05-06": ["SBET", "LXEH", "PONY", "AIFU", "GDEV", "CDLX", "RYM", "ABTC", "BIVI", "WRD", "LOBO", "QNTM", "AEVA", "EVGO", "DHC", "CTMX", "UEIC", "FNGR", "FULC", "SSP", "XRX", "SIBN", "PRPL", "UPWK", "BCRX"],
    // "2025-05-07": ["SBET", "PRCH", "PONY", "LXEH", "GDEV", "CDLX", "RYM", "ABTC", "SKIN", "ATOM", "AIFU", "UEIC", "OPAL", "PRPL", "ANGI", "FNGR", "EOSE", "DHC", "EVGO", "BIVI", "WRD", "KE", "AEVA", "SIBN", "ALMS"],
    // "2025-05-08": ["SBET", "PONY", "PRCH", "RYM", "DAVE", "LXEH", "ABTC", "OM", "GDEV", "SEDG", "ATOM", "BIVI", "LPRO", "SEZL", "CTMX", "AEVA", "ALMS", "UEIC", "STKL", "OPAL", "SSP", "APPS", "GRPN", "EVGO", "PSNL"],
    // "2025-05-09": ["SBET", "ABTC", "SKIN", "PRCH", "PONY", "DAVE", "SEZL", "SEDG", "IFBD", "LXEH", "AIFU", "UEIC", "GRPN", "LASR", "AEVA", "GOGO", "ANGI", "REFR", "APPS", "TTEC", "BTDR", "STKL", "BZUN", "DHC", "DH"],
    // "2025-05-10": ["SKIN", "PRCH", "PONY", "DAVE", "SEZL", "ABTC", "GRPN", "GOGO", "LXEH", "IFBD", "ANGI", "LASR", "AEVA", "APPS", "BTDR", "ATOM", "RPID", "TTEC", "DH", "REFR", "OUST", "LPRO", "QDEL", "STKL", "NRDS"],
    // "2025-05-11": ["SKIN", "SEZL", "DAVE", "GRPN", "LASR", "GOGO", "IFBD", "QDEL", "DH", "PONY", "REFR", "TTEC", "SEDG", "APPS", "CRVS", "LPRO", "ABTC", "OM", "RPID", "RUN", "PRCH", "PHAT", "OUST", "LYFT", "ALNT"],
    // "2025-05-12": ["ABTC", "JYD", "CTMX", "FMST", "GOGO", "LASR", "REFR", "TTSH", "GRPN", "SERV", "OM", "AEVA", "TTD", "TTEC", "FLNC", "PHAT", "ALLT", "LYFT", "ODP", "STKS", "DH", "MTRX", "OUST", "QDEL", "ARRY"],
    // "2025-05-13": ["ABTC", "LOBO", "CTMX", "JYD", "FMST", "LASR", "ARRY", "GOGO", "CONL", "MAXN", "OM", "FSLR", "VUZI", "SERV", "AEVA", "ALLT", "GRPN", "RENT", "RUN", "PHAT", "TSLL", "REFR", "HUMA", "FNGR", "FLNC"],
    // "2025-05-14": ["ABTC", "LOBO", "CTMX", "JYD", "SMCX", "FMST", "GOGO", "ARRY", "LASR", "OM", "CONL", "AEVA", "VUZI", "SEPN", "FNGR", "TSLL", "SWVL", "HUMA", "RUN", "FSLR", "SERV", "PAYS", "ACDC", "ALLT", "REFR"],
    // "2025-05-15": ["RNAZ", "ABTC", "LOBO", "FMST", "CTMX", "JYD", "SMCX", "AEVA", "OM", "RENT", "PAYS", "GOGO", "ARRY", "LASR", "EWCZ", "TRNR", "SEPN", "FNGR", "SERV", "HUMA", "RUN", "VUZI", "SWVL", "PHAT", "TSLL"],
    // "2025-05-16": ["RNAZ", "ABTC", "LOBO", "FMST", "SMCX", "JYD", "TSSI", "PHAT", "HUMA", "AEVA", "CTMX", "RENT", "SERV", "SWVL", "CONL", "QUBT", "GRNQ", "SEPN", "EWCZ", "ACDC", "SMCI", "RUN", "TRNR", "TSLL", "CRWV"],
    // "2025-05-17": ["RNAZ", "LOBO", "FMST", "TSSI", "SMCX", "HUMA", "SWVL", "AEVA", "CONL", "RENT", "SEPN", "GRNQ", "CRWV", "EWCZ", "CAPR", "SMCI", "QUBT", "VUZI", "HOWL", "LWLG", "NPCE", "SERV", "TNGX", "TRNR", "PAYS"],
    // "2025-05-18": ["RNAZ", "SMCX", "TSSI", "SWVL", "GRNQ", "FMST", "SEPN", "QUBT", "HUMA", "AEVA", "EWCZ", "CRWV", "GORV", "SMCI", "PHAT", "LWLG", "ACAD", "NPCE", "CONL", "VUZI", "APLD", "CREX", "RENT", "BIRD", "CAPR"],
    // "2025-05-19": ["RNAZ", "TNGX", "FMST", "ARQQ", "TSSI", "GRNQ", "TMC", "SWVL", "ABTC", "QNTM", "GORV", "ENGN", "CAPR", "QUBT", "CRWV", "CRBU", "LWLG", "DOGZ", "EVLV", "LAES", "ACAD", "ATAI", "PHAT", "TRNR", "RAPT"],
    // "2025-05-20": ["TNGX", "ABTC", "ARQQ", "CAPR", "TMC", "RLMD", "ATAI", "LAES", "ENGN", "QNTM", "CRBU", "FOSL", "TSSI", "PHAT", "BDSX", "GORV", "VTYX", "INV", "SMLR", "CRWV", "QUBT", "AISP", "FATE", "NVAX", "AURA"],
    // "2025-05-21": ["AIFU", "BDSX", "ARQQ", "TNGX", "ABTC", "CRWV", "CAPR", "QNTM", "TMC", "LAES", "SMLR", "RLMD", "UPXI", "EVLV", "ENGN", "ATAI", "GORV", "TSSI", "AURA", "NYXH", "FMST", "VTYX", "AKRO", "CGC", "ACAD"],
    // "2025-05-22": ["AIFU", "NVTS", "BDSX", "ABTC", "ARQQ", "TNGX", "RLMD", "LAES", "VTYX", "CRWV", "CREX", "CAPR", "QNTM", "FMST", "TMC", "UPXI", "SMLR", "TSSI", "ENGN", "CMTL", "ATAI", "QUBT", "CGC", "INV", "CRBU"],
    // "2025-05-23": ["AIFU", "NVTS", "SBET", "GORV", "RLMD", "BDSX", "ARQQ", "RAPT", "CREX", "CRWV", "LAES", "SMLR", "NEUP", "VTYX", "INV", "TNGX", "FCEL", "MRUS", "QSI", "TMC", "NNE", "ORIC", "ASPI", "HUMA", "GTBP"],
    // "2025-05-24": ["AIFU", "NVTS", "SBET", "RAPT", "CREX", "GORV", "LAES", "RLMD", "TNGX", "ARQQ", "NNE", "NEUP", "QSI", "FCEL", "CRWV", "ORIC", "SBC", "MRUS", "TMC", "DOMO", "CMTL", "UROY", "URGN", "ENGN", "ETNB"],
    // "2025-05-25": ["AIFU", "NVTS", "SBET", "GORV", "CREX", "RAPT", "NEUP", "RLMD", "NNE", "MRUS", "SBC", "QSI", "ASPI", "DOMO", "BDSX", "GTBP", "ETNB", "BGM", "UROY", "NIU", "EU", "AKRO", "ORIC", "PTON", "SMTK"],
    // "2025-05-26": ["NVTS", "SBET", "AIFU", "GORV", "CREX", "NNE", "RAPT", "DOMO", "SBC", "GTBP", "MRUS", "EU", "FCEL", "FMST", "URBN", "NIU", "ASPI", "NEUP", "UROY", "RGTI", "URGN", "BGM", "EVO", "CRWV", "QUBT"],
    // "2025-05-27": ["SBET", "GORV", "IRBT", "CREX", "NVTS", "DOMO", "FCEL", "NNE", "FMST", "SBC", "EU", "RLMD", "RGTI", "PONY", "PCT", "NOTV", "SERV", "SLDP", "OPAL", "QSI", "QUBT", "APYX", "VUZI", "FIP", "WALD"],
    // "2025-05-28": ["SBET", "ASPS", "CLGN", "GORV", "FMST", "OPAL", "IRBT", "RLMD", "DOMO", "NVTS", "MNRO", "SLDP", "CREX", "FCEL", "EU", "NLSP", "SBC", "RYM", "MASS", "RGTI", "NNE", "PCT", "EDIT", "ONDS", "FIP"],
    // "2025-05-29": ["SBET", "ASPS", "HBIO", "CLGN", "GORV", "OPAL", "FMST", "RLMD", "ORIC", "NOTV", "IRBT", "DOMO", "SBC", "IMAB", "NLSP", "MRUS", "MNRO", "VUZI", "DXLG", "CREX", "SLDP", "EU", "MASS", "BRNS", "ATXS"],
    // "2025-05-30": ["SBET", "ASPS", "CLGN", "RRGB", "HBIO", "GORV", "FMST", "OPAL", "ORIC", "ONDS", "SBC", "LOOP", "EYPT", "NOTV", "IMAB", "PAYS", "IRBT", "BRNS", "CTMX", "TONX", "NVTS", "VUZI", "ACDC", "RLMD", "MNRO"],
    // "2025-05-31": ["ASPS", "SBET", "CLGN", "RRGB", "BRNS", "HBIO", "FMST", "IMAB", "ONDS", "TONX", "OPAL", "PAYS", "ORIC", "NVTS", "SVRA", "LOOP", "EYPT", "ACDC", "IRBT", "MNRO", "STRZ", "BAER", "ATXS", "GORV", "DOOO"],
    // "2025-06-01": ["SBET", "CLGN", "RRGB", "HBIO", "BRNS", "ORIC", "ERAS", "ONDS", "TONX", "SVRA", "IMAB", "CTMX", "STRZ", "EYPT", "DOOO", "LOOP", "QNTM", "ACDC", "JFIN", "GNLN", "BAER", "ATXS", "SLN", "OCUL", "ATYR"],
    // "2025-06-02": ["LYEL", "SBET", "VERA", "RRGB", "HBIO", "KYMR", "APLD", "ONDS", "TNGX", "BCAB", "QNTM", "ERAS", "TONX", "LOOP", "ISPO", "ALXO", "TBPH", "IMCR", "AVTX", "BRNS", "SVRA", "RGNX", "STRZ", "VYGR", "BAER"],
    // "2025-06-03": ["LYEL", "BMEA", "VERA", "APLD", "KYMR", "RAPP", "TNGX", "IMAB", "CRWV", "RRGB", "ONDS", "AENT", "BCAB", "FMST", "ABVX", "NIPG", "CTRN", "PPTA", "ATYR", "CENX", "MLTX", "CTXR", "TSSI", "RUN", "ELVN"],
    // "2025-06-04": ["LYEL", "BMEA", "APLD", "VERA", "ONDS", "RAPP", "KYMR", "CRWV", "RRGB", "LOOP", "TNGX", "FMST", "TSSI", "RCAT", "ABVX", "SPWH", "AENT", "CTKB", "MLTX", "IMAB", "TONX", "CTRN", "NVTS", "ESPR", "IBIO"],
    // "2025-06-05": ["LYEL", "APLD", "BMEA", "VERA", "IMAB", "KYMR", "FMST", "ONDS", "LOOP", "TNGX", "RAPP", "RRGB", "SPWH", "DPRO", "ABVX", "TSSI", "MFH", "TONX", "ESPR", "CAPR", "HSDT", "ASTS", "AIFU", "CTKB", "AENT"],
    // "2025-06-06": ["PHAT", "IMAB", "TNGX", "BMEA", "LYEL", "APLD", "URGN", "RENT", "DPRO", "SPWH", "BTAI", "RAPP", "VTYX", "PRME", "TNYA", "ESPR", "CAPR", "TSSI", "MFH", "GDEV", "NBIS", "ALGS", "LOOP", "ABVX", "AIFU"],
    // "2025-06-07": ["PHAT", "IMAB", "LYEL", "BMEA", "TNGX", "URGN", "RENT", "DPRO", "CAPR", "TNYA", "PRME", "SPWH", "BTAI", "GDEV", "ALGS", "KRRO", "CGC", "APLD", "RAPP", "TSSI", "MFH", "NBIS", "AIFU", "FCEL", "FTRE"],
    // "2025-06-08": ["PHAT", "LYEL", "DPRO", "URGN", "RENT", "IMAB", "CGC", "APLD", "GDEV", "BTAI", "TSSI", "TNGX", "GRRR", "TNYA", "SPWH", "PRME", "NBIS", "SCNX", "CAPR", "AIFU", "APPS", "IPX", "RXRX", "VTYX", "ALGS"],
    // "2025-06-09": ["BOLT", "DUO", "PHAT", "CTXR", "DPRO", "IMAB", "URGN", "HBIO", "NLSP", "GDEV", "FCEL", "CMBM", "PLUG", "TNYA", "GPRO", "VTYX", "TNGX", "BIRD", "BTAI", "CTOR", "ZBIO", "FDMT", "NBIS", "SPWH", "PRME"],
    // "2025-06-10": ["BOLT", "DUO", "PHAT", "DPRO", "HBIO", "PLUG", "BIRD", "IRWD", "URGN", "RDNW", "CTOR", "IOVA", "SSP", "QTRX", "BTAI", "NVTS", "FCEL", "TSLL", "ASPS", "KRRO", "BGM", "PMVP", "TNGX", "CMBM", "ABCL"],
    // "2025-06-11": ["BOLT", "DUO", "PHAT", "PLUG", "QUBT", "HBIO", "CTOR", "OUST", "URGN", "ABCL", "FFAI", "CNET", "INSM", "LAES", "TNGX", "QTRX", "BIRD", "PLAY", "ADV", "ASPS", "IRWD", "WRAP", "SPWH", "KLXE", "TSLL"],
    // "2025-06-12": ["BOLT", "DUO", "EMPD", "GNLN", "PHAT", "URGN", "CTOR", "PLUG", "QUBT", "BIRD", "ASPS", "SPWH", "TNGX", "HBIO", "OUST", "QNTM", "ABCL", "GRNQ", "YYAI", "INSM", "AXTI", "PLAY", "ALT", "ALGS", "IOVA"],
    // "2025-06-13": ["ONCO", "EMPD", "OP", "GNLN", "URGN", "CRML", "GRNQ", "ASPS", "KLXE", "PLUG", "ABCL", "VSAT", "INSM", "SPWH", "GPRE", "TSLL", "QNTM", "HBIO", "SEDG", "CVAC", "BIRD", "PLAY", "TORO", "NUWE", "FFAI"],
    // "2025-06-14": ["ONCO", "EMPD", "OP", "GNLN", "URGN", "KLXE", "CRML", "NUWE", "GRNQ", "ABCL", "QNTM", "GPRE", "CTOR", "ASPS", "ZBAI", "SPWH", "TORO", "CVAC", "ONDS", "OUST", "PHAT", "SEDG", "OSS", "AXTI", "RUN"],
    // "2025-06-15": ["ONCO", "EMPD", "OP", "URGN", "GNLN", "NUWE", "CRML", "QNTM", "CVAC", "KLXE", "ZBAI", "GRNQ", "TORO", "SPWH", "GPRE", "CVGW", "PHAT", "VSAT", "ASPS", "SINT", "RUN", "OABI", "ONDS", "IMPP", "CTOR"],
    // "2025-06-16": ["ONCO", "OP", "CRML", "URGN", "SATS", "QNTM", "GRNQ", "TMC", "VRA", "GPRE", "ILPT", "FWRD", "ELVN", "SINT", "VSAT", "PACB", "OSS", "CLMT", "AMBR", "EU", "ASTS", "SEDG", "ADSE", "ZYXI", "DOGZ"],
    // "2025-06-17": ["RAPT", "OP", "RELI", "CRML", "APPS", "SATS", "GEOS", "OSS", "QNTM", "VRA", "ILPT", "PCT", "KLXE", "GPRE", "CDLX", "ARQQ", "AMTX", "CLMT", "TMC", "NTLA", "ELVN", "ECX", "FLNC", "JBIO", "INVZ"],
    // "2025-06-18": ["RAPT", "OP", "RELI", "QNTM", "CONL", "CRML", "ARQQ", "TMC", "APPS", "SATS", "INVZ", "JBIO", "ILPT", "OSS", "SYM", "GEOS", "AIFU", "PRME", "URGN", "COIN", "NNE", "PCT", "ASTS", "AEVA", "LFMD"],
    // "2025-06-19": ["RAPT", "OP", "RELI", "QNTM", "CONL", "CRML", "ARQQ", "TMC", "APPS", "SATS", "INVZ", "JBIO", "ILPT", "OSS", "SYM", "GEOS", "AIFU", "PRME", "URGN", "COIN", "NNE", "PCT", "ASTS", "AEVA", "LFMD"],
    // "2025-06-20": ["RAPT", "OP", "RELI", "CTOR", "QNTM", "GEOS", "CRML", "CONL", "ARQQ", "INVZ", "SATS", "TMC", "PRME", "JBIO", "AAOI", "AIFU", "ILPT", "TSAT", "VVOS", "COIN", "TSSI", "APPS", "GRRR", "SSP", "CRWV"],
    // "2025-06-21": ["RAPT", "RELI", "CTOR", "QNTM", "GEOS", "ARQQ", "CONL", "AAOI", "INVZ", "TMC", "AIFU", "PRME", "JBIO", "TSSI", "ILPT", "TSAT", "VVOS", "CTXR", "GRRR", "APPS", "FLL", "COIN", "CRBU", "EMPD", "CRWV"],
    // "2025-06-22": ["RELI", "CTOR", "QNTM", "ARQQ", "GEOS", "CONL", "JBIO", "AAOI", "CTXR", "TSAT", "GRRR", "INVZ", "VVOS", "FLL", "SMX", "SMLR", "TMC", "COIN", "DPRO", "TSSI", "CUE", "EMPD", "AAPG", "PRME", "AIFU"],
    // "2025-06-23": ["GEOS", "CTOR", "CONL", "SMLR", "VVOS", "PRME", "AAOI", "TSAT", "CMTL", "SKIN", "WGS", "CTXR", "OUST", "RKLB", "ARQQ", "TSSI", "ASTS", "COIN", "JBIO", "DPRO", "TSLL", "AIFU", "CRMD", "EMPD", "CMPX"],
    // "2025-06-24": ["GEOS", "CTOR", "AIFU", "CTXR", "WGS", "RZLV", "PRME", "CAR", "SKIN", "TSAT", "CONL", "CMTL", "STKS", "AMLX", "PAYS", "LFCR", "OP", "HTZ", "APYX", "COMM", "RKLB", "NIPG", "ASTS", "AMBA", "SMLR"],
    // "2025-06-25": ["CTOR", "GEOS", "AIFU", "RZLV", "WGS", "OP", "CONL", "CAR", "CTXR", "SKIN", "PRME", "RAPT", "AAOI", "STKS", "COMM", "POET", "BMBL", "AVAV", "LFCR", "PAYS", "AMDL", "AMLX", "AMBA", "HTZ", "LXRX"],
    // "2025-06-26": ["CTOR", "GEOS", "CRML", "CONL", "RZLV", "CTXR", "NIPG", "AVAV", "PRME", "WGS", "CORZ", "CAR", "AAOI", "POET", "STKS", "COMM", "AIFU", "SKIN", "LPSN", "PAYS", "GTBP", "AMBA", "RAPT", "HSAI", "RKLB"],
    // "2025-06-27": ["GNLN", "INDP", "CTOR", "AEVA", "CORZ", "NIPG", "AVAV", "WGS", "RZLV", "CONL", "CAPR", "CTXR", "AIFU", "POET", "AMBA", "CAR", "COMM", "IREN", "PAYS", "LPSN", "AMLX", "VNET", "CRML", "AENT", "BMBL"],
    // "2025-06-28": ["GNLN", "INDP", "CTOR", "CORZ", "CTXR", "AIFU", "AVAV", "CAPR", "SMCX", "POET", "AEVA", "CRML", "AENT", "NIPG", "CONL", "AMBA", "RZLV", "IREN", "BMBL", "VNET", "NFE", "ALDX", "SEDG", "SGMO", "LPSN"],
    // "2025-06-29": ["GNLN", "INDP", "CTOR", "CORZ", "NIPG", "AVAV", "CRML", "LPSN", "AEVA", "CTXR", "CAPR", "SMCX", "TLS", "KALA", "NLSP", "UTSI", "POET", "EMPD", "IREN", "ONCO", "VNET", "DAKT", "ICCM", "ENVX", "SATS"],
    // "2025-06-30": ["GNLN", "INDP", "CTOR", "NFE", "NIPG", "CORZ", "TRNR", "PLUG", "ALT", "CTXR", "INVZ", "AEVA", "CRML", "CIFR", "NLSP", "IREN", "UTSI", "EOSE", "AVAV", "ONDS", "ENVX", "RLMD", "METC", "WGMI", "KTOS"],
    // "2025-07-01": ["NFE", "CTOR", "CTXR", "SCNX", "TRNR", "MNY", "AIFU", "ALT", "VVOS", "ATAI", "NIPG", "BOOM", "SEAT", "DNUT", "CMPS", "JBIO", "RUN", "BAER", "RRGB", "FLNC", "CIFR", "PLUG", "MGNI", "MNRO", "IMAB"],
    // "2025-07-02": ["SONN", "CTXR", "NFE", "MNY", "SCNX", "CTOR", "ABTC", "ALT", "CIFR", "AIFU", "TRNR", "GGR", "DNUT", "CMPS", "SBET", "HIVE", "RRGB", "BTBT", "ATAI", "GHRS", "MAXN", "QUBT", "SLNH", "VRA", "EDIT"],
    // "2025-07-03": ["SONN", "NFE", "CTXR", "ABTC", "MNY", "CTOR", "SCNX", "CIFR", "AIFU", "SBET", "AENT", "VVOS", "BTBT", "SEDG", "RUN", "ALT", "TRIP", "FLNC", "TRNR", "TLRY", "FLUX", "GGR", "SYM", "CMND", "SLNH"],
    // "2025-07-04": ["SONN", "ABTC", "MNY", "SCNX", "VVOS", "BTBT", "SHLS", "ALT", "SBET", "CIFR", "SEDG", "NFE", "AENT", "TLRY", "RUN", "TRIP", "FLNC", "ARRY", "FLUX", "CMND", "CTXR", "PRME", "SYM", "GNLN", "FFAI"],
    // "2025-07-05": ["SONN", "ABTC", "MNY", "SCNX", "SHLS", "AENT", "CTXR", "SBET", "SEDG", "TRIP", "BTBT", "ARRY", "TLRY", "HIVE", "CMND", "PRME", "CIFR", "RUN", "SLNH", "PACB", "FLNC", "MAXN", "STKS", "SYM", "BTDR"],
    // "2025-07-06": ["SONN", "SBET", "CMND", "TLRY", "AENT", "TRIP", "BTBT", "SEDG", "PACB", "AMTX", "MNY", "SYM", "BTDR", "TMC", "METC", "MAXN", "PSIX", "TONX", "DDOG", "GHRS", "SGML", "GGR", "AVXL", "RGTI", "VVOS"],
    // "2025-07-07": ["BIVI", "REVB", "SONN", "VVOS", "FLUX", "BTBT", "KALV", "TRNR", "COGT", "AENT", "AMTX", "RUN", "ZVRA", "GSIT", "APYX", "PRME", "ABTC", "GRNQ", "FFAI", "ENVX", "INBX", "BEEM", "IRBT", "VIVS", "ZBAI"],
    // "2025-07-08": ["ZBAI", "TRNR", "UPXI", "INBX", "SANA", "RYM", "ASPS", "SBET", "RILY", "OPEN", "GSIT", "SLNH", "ZVRA", "GGR", "IRBT", "CRBU", "VVOS", "CCCC", "SOUN", "IVA", "CLOV", "GRI", "FULC", "REVB", "BZAI"],
    // "2025-07-09": ["ASPS", "TRNR", "CCCC", "VVOS", "RYTM", "RILY", "SBET", "SANA", "REVB", "INBX", "UPXI", "GSIT", "CRBU", "TLRY", "PRME", "RNAC", "KALA", "IPWR", "GGR", "OPEN", "PLUG", "SSP", "RANI", "VIVS", "PTC"],
    // "2025-07-10": ["QTTB", "UPXI", "VVOS", "SLNH", "TRNR", "OPEN", "ASPS", "SBET", "VTYX", "RILY", "METC", "TORO", "KALA", "CCCC", "RYTM", "IPWR", "POET", "SANA", "INBX", "PRME", "GSIT", "RAPP", "REVB", "CRBU", "ZBAI"],
    // "2025-07-11": ["SLNH", "QTTB", "ZBAI", "UPXI", "SBET", "CCCC", "METCB", "TORO", "UXIN", "PHVS", "POET", "SANA", "VTYX", "VVOS", "RYTM", "ATHA", "RILY", "RMNI", "METC", "GRNQ", "NIPG", "IPWR", "LXRX", "RCAT", "OPEN"],
    // "2025-07-12": ["QTTB", "SLNH", "ZBAI", "UXIN", "METCB", "PHVS", "POET", "TORO", "GRNQ", "VVOS", "VTYX", "CCCC", "RMNI", "RXST", "METC", "RCAT", "ATHA", "UPXI", "INVZ", "LXRX", "ILPT", "OSS", "SWVL", "KALA", "IPWR"],
    // "2025-07-13": ["SLNH", "QTTB", "ZBAI", "UXIN", "PHVS", "GRNQ", "METCB", "UPXI", "RCAT", "SBET", "NEXT", "OSS", "TORO", "ONDS", "VVOS", "METC", "ATRO", "NFE", "CNET", "ILPT", "DPRO", "SONN", "IPX", "VTYX", "HOWL"],
    // "2025-07-14": ["GORV", "SONN", "IBG", "OP", "ZBAI", "RCAT", "QTTB", "UXIN", "METCB", "UPXI", "SBET", "CLLS", "SLNH", "METC", "IRBT", "PHVS", "NEXT", "ONDS", "QNTM", "OPEN", "ILPT", "ZBIO", "OSS", "HOWL", "LTRN"],
    // "2025-07-15": ["GORV", "SONN", "IBG", "CMBM", "HTOO", "OP", "SBET", "CLLS", "CRML", "METC", "VNET", "KC", "RCAT", "UXIN", "SLDP", "OSS", "RAPT", "CLGN", "METCB", "NEXT", "HOWL", "MNY", "OPEN", "AMDL", "OUST"],
    // "2025-07-16": ["GORV", "SONN", "NUWE", "IBG", "SBET", "OP", "OPEN", "CMBM", "MNY", "DTST", "GBIO", "BRNS", "LWLG", "HTOO", "RCAT", "CRML", "VERI", "UPXI", "DPRO", "GRI", "METC", "OSS", "FFAI", "CLGN", "CLLS"],
    // "2025-07-17": ["GORV", "EMPD", "NUWE", "SONN", "ETHZ", "OPEN", "IBG", "DPRO", "SBET", "OP", "BEEM", "CMBM", "VERI", "BRNS", "MNY", "RCAT", "CRML", "LWLG", "UPXI", "FFAI", "DTST", "GBIO", "HTOO", "METC", "NVX"],
    // "2025-07-18": ["EMPD", "NUWE", "OPEN", "ETHZ", "IBG", "CMBM", "BZAI", "XPON", "VERI", "MNY", "BEEM", "SLDP", "CRML", "BRNS", "NVX", "DPRO", "MESO", "ASPI", "DTST", "RGTI", "RAPT", "CLGN", "PGY", "LCID", "UPXI"],
    // "2025-07-19": ["EMPD", "NUWE", "ETHZ", "OPEN", "CMBM", "BZAI", "XPON", "MNY", "DPRO", "VERI", "BRNS", "NVX", "CRML", "DTST", "BEEM", "BGM", "MESO", "SLDP", "LCID", "BIVI", "UPXI", "RGTI", "PGY", "LGO", "KOPN"],
    // "2025-07-20": ["EMPD", "ETHZ", "OPEN", "BZAI", "XPON", "VERI", "BRNS", "BEEM", "MESO", "CMBM", "SLNH", "UPXI", "MFH", "ASPI", "LCID", "YYAI", "DPRO", "PGY", "CUE", "LGO", "KOPN", "AVTX", "GLXY", "SMTK", "TNYA"],
    // "2025-07-21": ["ETHZ", "CMBM", "BZAI", "OPEN", "XPON", "BEEM", "BRNS", "NVX", "HSDT", "AVTX", "NVTS", "YYAI", "ATAI", "ALAB", "MAXN", "SMTK", "ABSI", "UGRO", "ABCL", "GPRO", "TBHC", "VERI", "METCB", "CLGN", "ATRA"],
    // "2025-07-22": ["GBIO", "HTOO", "CMBM", "OPEN", "GPRO", "CDLX", "TBHC", "MEDP", "UGRO", "WOOF", "NVTS", "LWLG", "YYAI", "DNUT", "IOVA", "ATRA", "JYD", "VERI", "AEHR", "MAXN", "PLCE", "ETHZ", "FFAI", "TLRY", "ATAI"],
    // "2025-07-23": ["GBIO", "ABVX", "GPRO", "YYAI", "HTOO", "CDLX", "CMBM", "IOVA", "DNUT", "TBHC", "OPEN", "UGRO", "WOOF", "AEHR", "MEDP", "PRPL", "ZSPC", "ATAI", "NVTS", "FLWS", "LWLG", "RAPT", "ETHZ", "CRBU", "XRX"],
    // "2025-07-24": ["GBIO", "ABVX", "GPRO", "YYAI", "HTOO", "CMBM", "CDLX", "DNUT", "OPEN", "UGRO", "KOD", "MEDP", "IOVA", "LWLG", "NVTS", "TBHC", "AEHR", "LESL", "MAXN", "ATAI", "SLDP", "JYD", "ICLR", "PRPL", "COSM"],
    // "2025-07-25": ["GBIO", "ABVX", "YYAI", "GPRO", "HTOO", "DNUT", "SMX", "KOD", "COSM", "CDLX", "MEDP", "FFAI", "LESL", "AEHR", "IOVA", "LWLG", "FTRE", "CLLS", "KALA", "ETHZ", "BDSX", "UGRO", "NBTX", "FLWS", "LQDA"],
    // "2025-07-26": ["ABVX", "YYAI", "GPRO", "SMX", "KOD", "DNUT", "COSM", "FFAI", "LESL", "KALA", "CLLS", "NBTX", "FTRE", "FLWS", "ESPR", "ECX", "LWLG", "LYEL", "UPB", "LQDA", "RANI", "MFH", "BDSX", "RNAZ", "TKNO"],
    // "2025-07-27": ["YYAI", "SMX", "KOD", "KALA", "MFH", "COSM", "NBTX", "ETHZ", "HBIO", "UPB", "MBX", "ESPR", "ECX", "SCHL", "BDSX", "TREE", "MNY", "SGMO", "LYEL", "NNE", "PHAT", "RANI", "REPL", "VALN", "LQDA"],
    // "2025-07-28": ["MRSN", "IMA", "CELC", "SMX", "MFH", "YYAI", "COSM", "ANGH", "KALA", "LOOP", "FNGR", "GEOS", "UPLD", "SMCX", "ETHZ", "SRPT", "LYEL", "RANI", "CLLS", "TONX", "UGRO", "UPB", "LESL", "ALXO", "GNLN"],
    // "2025-07-29": ["MRSN", "IMA", "CELC", "SMX", "MFH", "COSM", "ETHZ", "SRPT", "KALA", "GEOS", "QCLS", "YYAI", "UPLD", "LOOP", "SMCX", "ANGH", "CLLS", "ECX", "RANI", "FNGR", "AMDL", "BELFB", "UPB", "SANM", "ENLV"],

    "2025-07-31": ["MRSN", "IMA", "CELC", "MFH", "SMX", "COSM", "ETHZ", "SRPT", "TOYO", "YYAI", "LXEH", "GEOS", "LOOP", "CECO", "UPB", "AMSC", "PI", "SMCX", "ECX", "WGS", "ENLV", "REPL", "FTAI", "RANI", "WING"],
    "2025-08-01": ["MRSN", "IMA", "CELC", "LXEH", "SMX", "TOYO", "COSM", "ETHZ", "SRPT", "MFH", "REPL", "LOBO", "FDMT", "YYAI", "GEOS", "CLLS", "CECO", "WGS", "ATEC", "PI", "INDV", "CRVO", "FTAI", "ENLV", "IMAB"],
    // "2025-08-02": ["LXEH", "ETHZ", "TOYO", "MFH", "SRPT", "FDMT", "REPL", "LOBO", "ATAI", "WGS", "CECO", "ATEC", "COSM", "INDV", "WING", "IMAB", "PI", "IRTC", "ALNY", "AMSC", "ENLV", "APPF", "KNSA", "AVTX", "YYAI"],
    // "2025-08-03": ["LXEH", "TOYO", "LOBO", "REPL", "FDMT", "IMAB", "WING", "COSM", "VVOS", "INDV", "APLD", "APPF", "ATEC", "ALNY", "AMSC", "MFH", "PI", "IRTC", "APLS", "AVTX", "FTAI", "LTRN", "AUPH", "TILE", "ATAI"],
    "2025-08-04": ["TONX", "COMM", "LXEH", "IMAB", "ONDS", "APLD", "VSAT", "ATEC", "AVTX", "LOBO", "LTRN", "PI", "GP", "VERI", "AMSC", "TOYO", "AUPH", "ATAI", "APLS", "ALNY", "INDV", "APPF", "TSSI", "QNTM", "OPEN"],
    "2025-08-05": ["COMM", "TONX", "IMAB", "LOBO", "STAA", "ATEC", "FMST", "ONDS", "XMTR", "FDMT", "VSAT", "BTAI", "AIP", "GP", "LXEH", "CSTL", "TCMD", "SNDX", "SNBR", "AUPH", "AVTX", "LTRN", "TILE", "ISPO", "HLMN"],
    "2025-08-06": ["COMM", "TONX", "IMAB", "VSAT", "LXEH", "STAA", "BTAI", "ONDS", "LOBO", "MYGN", "EHTH", "ATON", "ATEC", "GO", "RIGL", "XMTR", "COSM", "LPSN", "ESPR", "SNBR", "FMST", "RNA", "FDMT", "SNDX", "YYAI"],
    "2025-08-07": ["COMM", "TONX", "IMAB", "VSAT", "LXEH", "ATON", "STAA", "BTAI", "MYGN", "LOBO", "AVAH", "ONDS", "RIGL", "SLDP", "GO", "ATEC", "XMTR", "ARHS", "LPSN", "SKYT", "FDMT", "FMST", "ISPO", "ESPR", "SNBR"],
    "2025-08-08": ["ZBAI", "COMM", "BTAI", "TONX", "LOBO", "ONDS", "MYGN", "AVAH", "VSAT", "STAA", "SKYT", "ATON", "IMAB", "RIGL", "ALEC", "BLZE", "LPSN", "ALAB", "ADV", "OPRX", "GO", "UPXI", "YYAI", "XERS", "SIGA"],
    // "2025-08-09": ["ZBAI", "BTAI", "AVAH", "ATON", "STAA", "MYGN", "SKYT", "ONDS", "LPSN", "ALEC", "BLZE", "ADV", "RIGL", "VSAT", "ASLE", "GO", "OPRX", "SIGA", "CSTL", "GCT", "XMTR", "YYAI", "WLDN", "LASR", "SBET"],
    // "2025-08-10": ["ZBAI", "BTAI", "AVAH", "MYGN", "ATON", "LPSN", "SKYT", "ALEC", "GO", "RIGL", "BLZE", "ADV", "OPRX", "ASLE", "SIGA", "VREX", "GCT", "ALAB", "ONDS", "YYAI", "ASTH", "EMBC", "LASR", "VSAT", "ARHS"],
    "2025-08-11": ["ZBAI", "BTAI", "AVAH", "IMXI", "TLS", "PBYI", "SKYT", "CGC", "ALEC", "TLRY", "SOUN", "ADV", "ASLE", "VREX", "GCT", "BLZE", "SKIN", "SIGA", "XERS", "LZ", "CLGN", "OPRX", "EMBC", "LASR", "ANIP"],
    "2025-08-12": ["ZBAI", "ETHZ", "TLS", "BTAI", "GEVO", "IMXI", "TLRY", "RDNW", "CGC", "PBYI", "SOUN", "VREX", "GRWG", "ALEC", "SKIN", "AMPH", "ADV", "GCT", "LASR", "BLZE", "EMBC", "AVAH", "ASTH", "WLDN", "SHC"],
    "2025-08-13": ["ZBAI", "ETHZ", "TLS", "TLRY", "WBTN", "BTAI", "GEVO", "IMXI", "SPNS", "PBYI", "CGC", "ARCT", "GBIO", "ALEC", "SOUN", "VREX", "SKIN", "GCT", "GRWG", "RDNW", "OUST", "AMPH", "EMBC", "ADV", "SLDP"],
    "2025-08-14": ["ZBAI", "ETHZ", "XPON", "TLS", "TLRY", "DOGZ", "WBTN", "ALEC", "WULF", "IMXI", "SPNS", "BTAI", "PBYI", "OPEN", "GEVO", "GBIO", "ARCT", "SLDP", "GRWG", "OUST", "SOUN", "VREX", "CGC", "DLO", "CRML"],
    "2025-08-15": ["ETHZ", "XPON", "TLS", "DOGZ", "PBYI", "OPEN", "FOSL", "WULF", "BTAI", "IMXI", "TNYA", "WBTN", "SPNS", "TLRY", "ARCT", "GEVO", "GBIO", "KPTI", "DLO", "RCEL", "RDNW", "ALEC", "FLGC", "GRWG", "IHRT"],
    // "2025-08-16": ["ETHZ", "XPON", "DOGZ", "TLS", "FOSL", "WULF", "OPEN", "WBTN", "TNYA", "ARCT", "GEVO", "GBIO", "PBYI", "KPTI", "RDNW", "BTAI", "SPNS", "DLO", "EDIT", "TLRY", "PRPL", "IMAB", "IHRT", "STOK", "ULCC"],
    // "2025-08-17": ["XPON", "ETHZ", "DOGZ", "FOSL", "WBTN", "TNYA", "WULF", "ARCT", "KPTI", "GBIO", "SPNS", "TLS", "DLO", "TONX", "OPEN", "UPXI", "IHRT", "KRRO", "ARRY", "PRPL", "STOK", "EDIT", "ULCC", "IPWR", "BRLT"],
    "2025-08-18": ["XPON", "FOSL", "DOGZ", "WULF", "ALXO", "OPEN", "TNYA", "ARRY", "GDRX", "RUN", "KPTI", "NERV", "DLO", "IBIO", "PRPL", "MRSN", "IMAB", "FLGC", "KE", "KOD", "SHLS", "TLSI", "GBIO", "CRML", "NUWE"],
    "2025-08-19": ["OPEN", "FOSL", "ARRY", "DOGZ", "RUN", "KPTI", "TNYA", "UPLD", "GDRX", "ALXO", "IPWR", "SHLS", "NERV", "KNDI", "KYIV", "SEDG", "TONX", "WULF", "CRML", "KOSS", "TLSI", "NXT", "IQ", "MFH", "KE"],
    "2025-08-20": ["DOGZ", "FOSL", "OPEN", "ARRY", "UPLD", "RUN", "TNYA", "KPTI", "TLSI", "WULF", "IPWR", "KNDI", "SHLS", "NERV", "TONX", "GDRX", "RCKT", "SEDG", "ALXO", "CRML", "IQ", "KE", "LVLU", "NXT", "MFH"],
    "2025-08-21": ["OPEN", "DOGZ", "ALXO", "FOSL", "ARRY", "RUN", "UPLD", "TNYA", "KPTI", "NERV", "ALGS", "GDRX", "IPWR", "TLSI", "WULF", "TONX", "CRML", "DRIO", "RCKT", "ZNTL", "IQ", "KNDI", "PRLD", "MFH", "SHLS"],
    "2025-08-22": ["ALXO", "UPLD", "RUN", "OPEN", "ARRY", "SHLS", "KPTI", "PRLD", "SEDG", "GDRX", "ZNTL", "ALGS", "DRIO", "AXTI", "NERV", "TLSI", "IQ", "NXT", "KNDI", "RDNW", "NESR", "FOSL", "INSG", "GEOS", "NBTX"],
    // "2025-08-23": ["ALXO", "OPEN", "UPLD", "PRLD", "AXTI", "DRIO", "ALGS", "INSG", "ZNTL", "RDNW", "LYTS", "GRWG", "ACMR", "IRWD", "NESR", "RCKT", "CIFR", "MFH", "SHLS", "ATAI", "VIVS", "RENT", "MURA", "RIOT", "NIPG"],
    // "2025-08-24": ["ALXO", "UPLD", "AXTI", "PRLD", "OPEN", "DRIO", "LYTS", "ZNTL", "RCKT", "TIGR", "ACMR", "CLMT", "ALEC", "RENT", "PHAT", "UPXI", "FIP", "VIVS", "NFE", "AMLX", "MURA", "DNTH", "RDNW", "IBIO", "ALGS"],
    "2025-08-25": ["PRLD", "AEHR", "OPEN", "ONDS", "GPRO", "DUO", "LXEH", "TLRY", "DRIO", "AXTI", "ALXO", "IREN", "TIGR", "CLMT", "LWLG", "CLGN", "FIP", "LYTS", "MFH", "ATAI", "MDXH", "ABTC", "ICCM", "BDSX", "UPXI"],
    "2025-08-26": ["CMMB", "SATS", "LWLG", "AEHR", "OPEN", "GPRO", "LXEH", "TLRY", "CLGN", "ONDS", "GPRE", "ALXO", "UPXI", "VERI", "KOPN", "MDXH", "TYRA", "ALGS", "DRIO", "NSSC", "CTOR", "CIFR", "ATAI", "METC", "CGC"],
    "2025-08-27": ["CMMB", "SATS", "LWLG", "LXEH", "CLGN", "NEUP", "AEHR", "GPRO", "MDB", "ALXO", "ONDS", "AFCG", "VERI", "OPEN", "INO", "TLRY", "GPRE", "CTOR", "DOMO", "ALGS", "INSG", "NSSC", "HCAT", "TYRA", "ENVB"],
    "2025-08-28": ["DRIO", "CMMB", "SATS", "LWLG", "NEUP", "RYM", "AEHR", "CGC", "ONDS", "ABTC", "LXEH", "MDB", "GPRE", "MFH", "CLGN", "TLRY", "OPEN", "KLRS", "GPRO", "IVA", "ICCM", "ALXO", "BLNK", "INO", "EDAP"],
    "2025-08-29": ["DRIO", "CMMB", "SATS", "DUO", "RLMD", "EDAP", "NEUP", "RYM", "KLRS", "LWLG", "ONDS", "MFH", "LXEH", "MDB", "BRLT", "AEHR", "CGC", "NEO", "IVA", "IREN", "GPRE", "VERI", "OPEN", "CTOR", "ABTC"],
    // "2025-08-30": ["DRIO", "CMMB", "SATS", "RLMD", "DUO", "RYM", "KLRS", "NEUP", "EDAP", "LXEH", "MDB", "LWLG", "MFH", "BRLT", "NEO", "CGC", "GPRO", "VERI", "IVA", "GDEV", "SMTK", "BCAB", "IREN", "ONDS", "PSNY"],
    // "2025-08-31": ["DRIO", "RLMD", "EDAP", "NEUP", "KLRS", "RYM", "DUO", "MDB", "LWLG", "BRLT", "NEO", "MFH", "IVA", "SMTK", "VERI", "KALA", "PSNY", "VIVS", "ONDS", "INV", "BCAB", "WOOF", "INO", "GDEV", "CGC"],
    "2025-09-01": ["DRIO", "RLMD", "DUO", "KLRS", "RYM", "EDAP", "NEUP", "VIVS", "MFH", "NEO", "SMTK", "WOOF", "ABTC", "PSNY", "INV", "CGC", "KALA", "RZLV", "BLNK", "INO", "AMBA", "ONDS", "ICCM", "SFWL", "IVA"],
    "2025-09-02": ["LCID", "CTEC", "GNOM", "HEAL", "RNRG", "SMTK", "RLMD", "MLYS", "DUO", "EDAP", "UTHR", "BZUN", "CCG", "IONS", "CYTK", "MNKD", "RYM", "IREN", "KLRS", "VIVS", "KALA", "FBIO", "MFH", "NEO", "UPB"],
    "2025-09-03": ["LCID", "ABTC", "CTEC", "GNOM", "HEAL", "RNRG", "RLMD", "MLYS", "SMTK", "EDAP", "DUO", "KALA", "PRTS", "UGRO", "KLRS", "BZUN", "CCG", "IONS", "SINT", "VIVS", "CYTK", "UTHR", "MFH", "NEUP", "RZLV"],
    "2025-09-04": ["LCID", "ABTC", "CTEC", "GNOM", "HEAL", "RNRG", "SMTK", "MLYS", "RLMD", "DUO", "EDAP", "DLTH", "KALA", "KLRS", "PRTS", "OPEN", "IONS", "CCG", "BZUN", "RZLV", "CYTK", "AIFU", "WRAP", "KRRO", "UTHR"],
    "2025-09-05": ["LCID", "ABTC", "CTEC", "GNOM", "HEAL", "RNRG", "MLYS", "DUO", "SMTK", "RLMD", "DLTH", "OLMA", "OPEN", "FBIO", "IONS", "CYTK", "VIVS", "KRRO", "KALA", "EDAP", "UTHR", "CCG", "SINT", "SNDK", "PRTS"],
    // "2025-09-06": ["ABTC", "SMTK", "DLTH", "DUO", "OPEN", "OLMA", "MLYS", "RLMD", "KRRO", "SINT", "FBIO", "PRTS", "SNDK", "ALEC", "BEAM", "ARWR", "SPWH", "ZBIO", "VYGR", "AVTX", "IONS", "TVTX", "AIFU", "LOOP", "ZUMZ"],
    // "2025-09-07": ["DLTH", "KRRO", "DUO", "SMTK", "OLMA", "SNDK", "AVTX", "OPEN", "PRTS", "SPWH", "BEAM", "KOD", "MLYS", "TNYA", "ALXO", "ZUMZ", "BCAB", "FBIO", "CGON", "EYPT", "LOOP", "FULC", "AIFU", "WALD", "GRI"],
    "2025-09-08": ["OXLC", "RAPP", "DUO", "DLTH", "DMAC", "DNTH", "LOOP", "INOD", "KRRO", "TBHC", "SNDK", "SATS", "ZBIO", "SMX", "PLCE", "OLMA", "GSAT", "SBC", "FBIO", "AIFU", "INVZ", "EGAN", "DOGZ", "MLYS", "BRZE"],
    "2025-09-09": ["OXLC", "RAPP", "TRML", "NBIS", "DNTH", "BCAB", "VERI", "DUO", "VIVS", "ABTC", "DMAC", "TBHC", "CNTA", "FCEL", "EGAN", "IFBD", "KRRO", "RZLV", "MFH", "ZBIO", "SATS", "INOD", "SKIN", "NEUP", "FNGR"],
    "2025-09-10": ["OXLC", "RAPP", "TRML", "VMEO", "DNTH", "MFH", "NBIS", "VIVS", "FCEL", "RZLV", "CNTA", "PLCE", "PBPB", "DUO", "VERI", "INOD", "BCAB", "TRVI", "CIFR", "DMAC", "CRWV", "TBHC", "ABTC", "TVTX", "SLNH"],
    "2025-09-11": ["OXLC", "RAPP", "TRML", "VMEO", "OPEN", "VIVS", "FCEL", "BCAB", "RZLV", "DNTH", "SLNH", "TBHC", "NBIS", "CNTA", "DUO", "INOD", "MFH", "GRI", "WBD", "PBPB", "GPRO", "SONN", "COSM", "PLCE", "TRVI"],
    "2025-09-12": ["SONN", "TRML", "VMEO", "FCEL", "VIVS", "WBD", "RZLV", "DNTH", "NBIS", "SLNH", "COSM", "VERI", "CIFR", "YYAI", "BCAB", "MFH", "ZBAI", "HIVE", "INOD", "GPRO", "PBPB", "OPEN", "GP", "TBHC", "APLD"],
    // "2025-09-13": ["VMEO", "SONN", "VIVS", "FCEL", "WBD", "OPEN", "COSM", "HIVE", "VERI", "SLNH", "PBPB", "RZLV", "YYAI", "ZBAI", "LAES", "IBG", "CIFR", "DAKT", "CNET", "QNTM", "INOD", "KALA", "HSDT", "TSLL", "BCAB"],
    // "2025-09-14": ["SONN", "WBD", "OPEN", "YYAI", "VIVS", "KALA", "QNTM", "FCEL", "COSM", "ZBAI", "GPRO", "TSLL", "HIVE", "RCAT", "IBG", "SLNH", "AISP", "PSKY", "BZUN", "JYD", "WRAP", "AMRK", "CNET", "IRWD", "HSDT"],
    "2025-09-15": ["HSDT", "RCEL", "WBD", "RELI", "SONN", "SLNH", "GLUE", "VIVS", "GPRO", "TSLL", "CCCC", "CDLX", "IHRT", "ZBAI", "TSAT", "OPEN", "LAES", "LAZR", "BRY", "HIVE", "STRZ", "PSKY", "FRGT", "BLNK", "VERI"],
    "2025-09-16": ["HSDT", "FLUX", "SONN", "WBTN", "RCEL", "SLNH", "CCG", "GLUE", "RELI", "CDLX", "TSLL", "GORV", "MFH", "CCCC", "IHRT", "KLRS", "TSAT", "BRY", "LAES", "RGTI", "AXTI", "LAZR", "AENT", "SRTA", "APPS"],
    "2025-09-17": ["HSDT", "SONN", "WBTN", "FLUX", "SLNH", "BGM", "ZBAI", "NFE", "CCG", "MFH", "GLUE", "RCEL", "LAZR", "TSLL", "PLUG", "RGTI", "LAES", "CDLX", "CCCC", "BRY", "LYFT", "BLDP", "CIFR", "SRTA", "ECX"],
    "2025-09-18": ["ATHA", "HSDT", "CDLX", "ETNB", "SONN", "NFE", "WBTN", "GLUE", "RGTI", "FLUX", "NTLA", "CCG", "BGM", "PLUG", "SRTA", "QNTM", "MFH", "CLSK", "SKYT", "FCEL", "IHRT", "RAPT", "RCEL", "LAZR", "BLDP"],
    "2025-09-19": ["ATHA", "CDLX", "ETNB", "SLNH", "NFE", "QMCO", "WBTN", "RGTI", "FLUX", "VERI", "BGM", "CCG", "PLUG", "NNE", "QUBT", "PONY", "NTLA", "SRTA", "GDEV", "LWLG", "CLSK", "FLNC", "BLDP", "IPWR", "SKYT"],
    // "2025-09-20": ["ATHA", "CDLX", "ETNB", "NFE", "QMCO", "RGTI", "QUBT", "GDEV", "PLUG", "VERI", "LWLG", "WRAP", "NTLA", "BGM", "CLSK", "IPWR", "HSDT", "LAES", "MFH", "CCG", "CHRS", "FCEL", "BLDP", "PRME", "NNE"],
    // "2025-09-21": ["ATHA", "CDLX", "ETNB", "QMCO", "VERI", "RGTI", "QUBT", "GDEV", "LWLG", "NNE", "IPWR", "PLUG", "LAES", "ARQQ", "ADVM", "BHF", "FLNC", "BLDP", "FCEL", "BGM", "SINT", "NTLA", "WRAP", "CLSK", "AVTX"],
    "2025-09-22": ["MBX", "SLNH", "CDLX", "GDEV", "KOD", "LWLG", "RELI", "FLGC", "VUZI", "VERI", "QMCO", "FLNC", "CMBM", "NFE", "DUO", "NTLA", "PLUG", "ODP", "QSI", "ATOM", "UROY", "XPON", "AXTI", "HOWL", "MDXH"],
    "2025-09-23": ["IBG", "SLNH", "MBX", "GDEV", "SAVA", "KOD", "DRIO", "ADVM", "VERI", "MFH", "VUZI", "BGM", "IFBD", "QMCO", "KPTI", "REPL", "ODP", "ASTS", "PLUG", "HOWL", "FLNC", "RELI", "UROY", "RGTI", "LXEH"],
    "2025-09-24": ["SLNH", "QURE", "IBG", "MBX", "CLPT", "KOD", "DRIO", "GDEV", "ADVM", "QCLS", "HOWL", "SAVA", "XPON", "FLNC", "VERI", "NBTX", "RELI", "MFH", "ODP", "ASTS", "CMBM", "VUZI", "IREN", "RGTI", "IFBD"],
    "2025-09-25": ["QURE", "SLNH", "IBG", "MBX", "DRIO", "CLPT", "KOD", "MFH", "ADVM", "GDEV", "ALXO", "FLNC", "HOWL", "CTMX", "QCLS", "SAVA", "VERI", "ODP", "RGTI", "INDP", "SMTK", "NEUP", "RELI", "IREN", "TKNO"],
    "2025-09-26": ["IBG", "QURE", "SLNH", "MBX", "DRIO", "CLPT", "MFH", "GDEV", "KOD", "ADVM", "ALXO", "PRLD", "FLNC", "HOWL", "CTMX", "FLUX", "QCLS", "ADSE", "INDP", "SKYT", "SAVA", "NBTX", "ODP", "TKNO", "CRNX"],
    // "2025-09-27": ["IBG", "QURE", "SLNH", "DRIO", "CLPT", "MFH", "KOD", "ALXO", "PRLD", "FLUX", "CTMX", "HOWL", "GDEV", "RAPT", "QCLS", "CRNX", "SAVA", "VTYX", "REPL", "SKYT", "ADSE", "SMTK", "ZVRA", "INDP", "NBTX"],
    // "2025-09-28": ["IBG", "QURE", "CLPT", "MFH", "ALXO", "DRIO", "QCLS", "CTMX", "PRLD", "CDLX", "CRNX", "SRRK", "RAPT", "REPL", "KLRS", "INDP", "FLUX", "NEUP", "CLGN", "INTC", "CRVS", "IAS", "NBTX", "INBX", "BGM"],
    "2025-09-29": ["LESL", "IBG", "ENTA", "DWTX", "DRIO", "FLUX", "CTMX", "TLRY", "QURE", "PRLD", "MFH", "MRUS", "BRNS", "ALXO", "CLPT", "KLRS", "BCAX", "STKS", "GDEV", "SGMO", "GRAL", "CLGN", "CDLX", "CRBU", "ACB"],
    "2025-09-30": ["LESL", "IBG", "ENTA", "MFH", "DRIO", "DWTX", "PRLD", "TLRY", "MRUS", "BCAX", "GDEV", "ANAB", "CTMX", "DPRO", "GRAL", "SKYT", "NBTX", "KLRS", "ORKA", "FATE", "STKS", "KRRO", "APPS", "LYEL", "SMTC"],
    "2025-10-01": ["LESL", "IBG", "ENTA", "DRIO", "MFH", "DWTX", "DPRO", "PRLD", "GDEV", "BCAX", "ANAB", "CTMX", "MRUS", "TORO", "TLRY", "GRAL", "KLRS", "OLMA", "SKYT", "SMCX", "VTYX", "BRNS", "PLUG", "RLMD", "ABCL"],
    "2025-10-02": ["LESL", "IBG", "ENTA", "DRIO", "GDEV", "MFH", "DPRO", "RLMD", "KLRS", "BCAX", "DWTX", "PRLD", "MRUS", "GRAL", "ANAB", "CTMX", "TORO", "SKYT", "ABSI", "NBTX", "CONL", "OLMA", "TLRY", "SMCX", "INOD"],
    "2025-10-03": ["LESL", "MFH", "ENTA", "GDEV", "FEMY", "DPRO", "PLUG", "BCAX", "NEUP", "DWTX", "CONL", "CLPT", "RLMD", "MRUS", "KLRS", "ANAB", "TLRY", "PRLD", "DRIO", "UPXI", "NBTX", "LYEL", "GRAL", "ASTS", "IBG"],
    // "2025-10-04": ["ENTA", "BYND", "FEMY", "MFH", "NEUP", "PLUG", "DPRO", "BCAX", "QCLS", "CONL", "LYEL", "CLLS", "ASTS", "ARQQ", "KALA", "UPXI", "ANAB", "NBTX", "TORO", "GRAL", "ATOM", "SMTK", "BLNK", "GSIT", "BLDP"],
    // "2025-10-05": ["FEMY", "NEUP", "PLUG", "MFH", "QCLS", "ARQQ", "SMTK", "ASTS", "RGTI", "MLTX", "BYND", "FCEL", "BLDP", "GSIT", "TORO", "CONL", "UPXI", "QUBT", "ATOM", "CLPT", "LWLG", "VUZI", "LAES", "ONDS", "ALXO"],
    "2025-10-06": ["GGR", "FEMY", "CRML", "PLUG", "SMTK", "AMDL", "NEUP", "SLDP", "MFH", "BLNK", "KOPN", "HUMA", "BZAI", "NVX", "RGTI", "GORV", "ARQQ", "RCAT", "KLRS", "FLNC", "NNE", "ONDS", "APYX", "TORO", "HIVE"],
    "2025-10-07": ["GGR", "FEMY", "MFH", "SLDP", "AMDL", "NVX", "VELO", "BZAI", "HIVE", "SMTK", "EGAN", "CRML", "RGTI", "ONDS", "NNE", "PLUG", "RCAT", "NEUP", "KOPN", "APYX", "BLNK", "ARQQ", "AMTX", "TMC", "FLUX"],
    "2025-10-08": ["GGR", "ATON", "FEMY", "AMDL", "GTBP", "CRML", "MFH", "SLDP", "VELO", "NVX", "HIVE", "BZAI", "RNAZ", "FLUX", "POET", "SMTK", "QTTB", "EGAN", "ONDS", "ATYR", "AMD", "CLPT", "BCAB", "KOPN", "RGTI"],
    "2025-10-09": ["GGR", "ATON", "FEMY", "CRML", "AMDL", "NVX", "MFH", "HIVE", "ZSPC", "SLDP", "SMTK", "BCAB", "QTTB", "FLUX", "RNAZ", "LAES", "RGTI", "BZAI", "ASTS", "LWLG", "VELO", "SERV", "NBTX", "EGAN", "DPRO"],
    "2025-10-10": ["GGR", "NVX", "CRML", "ATON", "FEMY", "QTTB", "AMDL", "RNAZ", "HIVE", "FLUX", "SLDP", "ATYR", "APYX", "EGAN", "BCAB", "PTGX", "FATE", "BZAI", "ZSPC", "APGE", "GLUE", "LAES", "AMD", "APLD", "METC"],
    // "2025-10-11": ["ATON", "QTTB", "NVX", "RNAZ", "FLUX", "HIVE", "PTGX", "CRML", "SLDP", "FATE", "APGE", "ATYR", "BCAB", "LAES", "GLUE", "TNYA", "APLD", "REFR", "ZSPC", "ORKA", "VELO", "CGEM", "POET", "ZBIO", "APYX"],
    // "2025-10-12": ["ATON", "NVX", "QTTB", "RNAZ", "CRML", "PTGX", "APGE", "GLUE", "DPRO", "ATYR", "ZSPC", "CGEM", "ASTS", "SLNH", "APLD", "NTLA", "ORKA", "ONCO", "METC", "FLUX", "EGAN", "AKRO", "TNYA", "POET", "REFR"],
    "2025-10-13": ["JYD", "CRML", "OP", "ASPI", "NVX", "LAES", "GLUE", "LGO", "APGE", "ZSPC", "QTTB", "CGEM", "IMAB", "CIFR", "NVTS", "APLD", "METC", "EOSE", "RGTI", "ORKA", "GGAL", "PTGX", "DPRO", "MRSN", "SAVA"],
    "2025-10-14": ["JYD", "CRML", "LAES", "NVTS", "ASPI", "SMTK", "UGRO", "ATXS", "VELO", "NVX", "OP", "GLUE", "RGTI", "LGO", "FLNC", "APLD", "QTTB", "TNGX", "RCKT", "POWI", "METC", "INDI", "DRCT", "ORKA", "QSI"],
    "2025-10-15": ["JYD", "OMER", "CRML", "NVTS", "VERI", "TRUE", "LAES", "SLNH", "FOSL", "FLNC", "QSI", "BIOX", "ATXS", "GLUE", "SMTK", "VELO", "OP", "ASPI", "TNGX", "APLD", "BTDR", "IBG", "SANA", "IRBT", "CGEM"],
    "2025-10-16": ["JYD", "PRAX", "OMER", "NVTS", "CRML", "TRUE", "SLNH", "LAES", "ATXS", "QSI", "WHWK", "OP", "VERI", "BIOX", "CRBP", "LOBO", "FLNC", "QCLS", "BTDR", "GLUE", "CGEM", "APLD", "TNGX", "SBFM", "IMAB"],
    "2025-10-17": ["JYD", "PRAX", "RANI", "OMER", "SLNH", "NVTS", "TRUE", "CRML", "KZR", "ATXS", "LOBO", "VERI", "QSI", "SBFM", "FLNC", "WHWK", "IRON", "IBG", "POWI", "INDI", "PZZA", "TNGX", "BIOX", "CRBP", "BTDR"],
    // "2025-10-18": ["PRAX", "RANI", "OMER", "SLNH", "TRUE", "NVTS", "CRML", "KZR", "ATXS", "VERI", "LOBO", "WHWK", "FLNC", "QSI", "BTDR", "SBFM", "POWI", "FEMY", "IRON", "QCLS", "SLN", "ATAI", "TNGX", "ENVB", "ABSI"],
    // "2025-10-19": ["PRAX", "RANI", "OMER", "SLNH", "TRUE", "KZR", "FEMY", "VERI", "SBFM", "BTDR", "WHWK", "LOBO", "ABSI", "KOD", "BIOX", "IRON", "FLNC", "SANA", "STRO", "ENVB", "ATAI", "IRBT", "JBHT", "TXMD", "QCLS"],
    "2025-10-20": ["RANI", "PRAX", "GSIT", "REPL", "WHWK", "CELC", "KZR", "RAPT", "KOD", "STRO", "CTXR", "GRAL", "SLNH", "NVTS", "SANA", "LOBO", "CCCC", "PSNL", "AVTX", "PACB", "SLN", "SVRA", "ABSI", "BEAM", "XNCR"],
    "2025-10-21": ["RANI", "NERV", "BYND", "GSIT", "REPL", "KZR", "STRO", "CELC", "RAPT", "IBIO", "NAUT", "KOD", "PRLD", "AVTX", "FEMY", "PRAX", "MGNX", "DCGO", "FLWS", "PLRX", "UTSI", "CCCC", "SVRA", "AVDL", "INVE"],
    "2025-10-22": ["RANI", "BYND", "NERV", "GSIT", "REPL", "IBIO", "YYAI", "CELC", "VICR", "KZR", "NDLS", "STRO", "DNUT", "LXEH", "RAPT", "ISRG", "AVDL", "KOD", "FLWS", "PRLD", "SABR", "PEGA", "IHRT", "BBGI", "PRAX"],
    "2025-10-23": ["RANI", "BYND", "SCNX", "NERV", "GSIT", "REPL", "VTYX", "IBIO", "VICR", "LXEH", "CELC", "KZR", "BIOA", "NDLS", "DNUT", "NAUT", "STRO", "FLWS", "AVTX", "ISRG", "TXMD", "RAPT", "RXT", "PI", "AVDL"],
    "2025-10-24": ["BYND", "SCNX", "NERV", "GSIT", "REPL", "VTYX", "RANI", "IBIO", "LXEH", "BIOA", "VICR", "CELC", "MOFG", "CLOV", "NDLS", "SNDK", "GTX", "FLWS", "SONN", "DRIO", "DNUT", "AXTI", "KOD", "PRLD", "CTXR"],
    // "2025-10-25": ["BYND", "SCNX", "NERV", "VTYX", "GSIT", "IBIO", "LXEH", "VICR", "BIOA", "MOFG", "PRLD", "NDLS", "CLOV", "GTX", "SONN", "DNUT", "OP", "SNDK", "MBX", "IVA", "FLWS", "NAUT", "GEOS", "IHRT", "AXTI"],
    // "2025-10-26": ["SCNX", "BYND", "VTYX", "VICR", "BIOA", "MOFG", "LXEH", "NDLS", "GTX", "IBIO", "DNUT", "CLOV", "SNDK", "PRLD", "FLWS", "YYAI", "IRBT", "IVA", "AXTI", "PEGA", "SONN", "KALU", "REFR", "ISRG", "RXT"],
    "2025-10-27": ["SCNX", "VTYX", "GGAL", "SONN", "RNA", "DYN", "IBIO", "REFR", "LXEH", "BIOA", "MOFG", "IVA", "SMLR", "ETHZ", "GTX", "LAZR", "ABTC", "GLUE", "CRESY", "DSGN", "VERI", "ZBIO", "ATOM", "AXTI", "PI"],
    "2025-10-28": ["ENVB", "GGAL", "SCNX", "RNA", "DYN", "MOFG", "AXTI", "SONN", "FRGT", "CRESY", "LVLU", "GLUE", "RELI", "HUT", "REFR", "ABTC", "AENT", "ARQT", "ETHZ", "QRHC", "AMDL", "CIFR", "LITE", "WULF", "ZBIO"],
    "2025-10-29": ["ENVB", "CMBM", "PPBT", "GGAL", "RNA", "SCNX", "DYN", "AXTI", "SNDK", "ACDC", "LITE", "AENT", "HUT", "INBX", "CRESY", "MBX", "GLUE", "AMDL", "NVDL", "NVDU", "MOFG", "ZEUS", "SONN", "ARQT", "REFR"],
    "2025-10-30": ["ENVB", "CMBM", "PPBT", "GGAL", "HBIO", "RNA", "DYN", "AXTI", "FORM", "MBX", "GH", "GLUE", "SNDK", "INBX", "ACDC", "MOFG", "IMVT", "KDK", "SCNX", "VIVS", "FLNC", "VIAV", "BIRD", "TER", "CRESY"],
    "2025-10-31": ["ENVB", "CMBM", "GGAL", "INBX", "PPBT", "RNA", "AXTI", "CSIQ", "DYN", "MNOV", "HBIO", "GH", "MBX", "IMVT", "VIAV", "CRESY", "DPRO", "IBIO", "FORM", "BIRD", "VTYX", "LAES", "LUNG", "ZEUS", "ETHZ"],
    // "2025-11-01": ["ENVB", "CMBM", "PPBT", "INBX", "MNOV", "VTYX", "CSIQ", "BIRD", "IBIO", "GH", "HBIO", "IMVT", "AXTI", "MBX", "VIAV", "FORM", "ZEUS", "WVE", "ARQT", "LUNG", "ACDC", "BHF", "ILMN", "AXGN", "TER"],
    // "2025-11-02": ["CMBM", "MNOV", "GH", "HBIO", "GSAT", "ILMN", "BIRD", "IRWD", "RANI", "CSIQ", "FORM", "BHF", "DPRO", "ACDC", "ARDX", "SLNH", "CHRW", "MBX", "TALK", "VIAV", "AXTI", "RYM", "INDV", "WVE", "INBX"],
    "2025-11-03": ["PRLD", "TERN", "RANI", "NAUT", "CSIQ", "MNOV", "ILMN", "IRWD", "GSAT", "AXTI", "ARDX", "CIFR", "CTMX", "SLDP", "TALK", "ATEC", "CNET", "BHF", "EOSE", "CRBU", "IREN", "AMKR", "MEOH", "BIRD", "SNCY"],
    "2025-11-04": ["TERN", "RANI", "DENN", "TCMD", "IHRT", "CSTL", "CSIQ", "HTZ", "LQDA", "IRWD", "XMTR", "CTMX", "AXTI", "ILMN", "MNOV", "TALK", "CIFR", "EVER", "BHF", "ATEC", "PRLD", "SANM", "UFPT", "AHCO", "AUPH"],
    "2025-11-05": ["TERN", "RANI", "SLDP", "TCMD", "DENN", "IHRT", "CSIQ", "FEMY", "CSTL", "IRWD", "CIFR", "AXTI", "BDSX", "IREN", "NPCE", "VCYT", "DAWN", "ILMN", "MNOV", "RIGL", "CTMX", "SANM", "HTZ", "GSAT", "XMTR"],
    "2025-11-06": ["TERN", "DENN", "RANI", "TCMD", "CSIQ", "IHRT", "GDEN", "MFH", "ALTO", "CSTL", "FEMY", "NPCE", "APPN", "STGW", "INV", "ESTA", "LFST", "XMTR", "DAWN", "SANM", "IRWD", "HTZ", "CTMX", "RDNW", "UXIN"],
    "2025-11-07": ["DENN", "IHRT", "TCMD", "QURE", "GDEN", "ALTO", "INV", "FEMY", "ORGO", "ESTA", "NPCE", "APPN", "NATR", "DAWN", "XMTR", "TERN", "RDNW", "CSTL", "LFST", "APYX", "FROG", "HTZ", "ABL", "CLPT", "CSIQ"],
    // "2025-11-08": ["FEMY", "GDEN", "ORGO", "NPCE", "ALTO", "RDNW", "CSIQ", "ESTA", "INV", "APPN", "DAWN", "NATR", "SEDG", "IHRT", "FROG", "LFST", "LITE", "SNDK", "ATNI", "ABL", "EOSE", "APYX", "BHF", "PLCE", "MFH"],
    // "2025-11-09": ["GDEN", "FEMY", "ORGO", "SONN", "APPN", "SEDG", "MFH", "NATR", "EOSE", "FROG", "ALTO", "ATNI", "IOVA", "LFST", "ABL", "SKYT", "INV", "PLCE", "CNTA", "MBX", "BHF", "DAWN", "GCT", "FHTX", "EXPE"],
    "2025-11-10": ["COGT", "ORGO", "NATR", "FROG", "SSP", "APPN", "SKYT", "AMTX", "GORV", "TXG", "APYX", "URGN", "PANL", "ATNI", "SNDK", "CSIQ", "PGNY", "EXPE", "GCT", "ABL", "FEMY", "IRWD", "RNAC", "EOSE", "GRWG"],
    "2025-11-11": ["COGT", "ORGO", "SRDX", "ENGN", "NATR", "IRWD", "SSP", "PUBM", "FROG", "APPN", "REAL", "TXMD", "GORV", "AMTX", "RPID", "URGN", "SNDK", "ATNI", "ABL", "INNV", "PANL", "APYX", "PGNY", "GRWG", "TXG"],
    "2025-11-12": ["COGT", "ORGO", "SRDX", "IRWD", "GORV", "NATR", "ENGN", "RPID", "SSP", "APPN", "TXMD", "RLMD", "URGN", "OPEN", "APYX", "FROG", "SNDK", "INNV", "REAL", "VERA", "PANL", "RNAC", "RDNW", "ATNI", "AMTX"],
    "2025-11-13": ["MRSN", "COGT", "GORV", "SRDX", "IRWD", "OPEN", "RLMD", "ENGN", "SSP", "RPID", "DRCT", "REAL", "NHTC", "SONN", "ALTO", "RDNW", "GTBP", "ONDS", "LVLU", "PUBM", "CLBT", "GSAT", "TXMD", "TRDA", "MRVI"],
    "2025-11-14": ["MRSN", "SRDX", "GTBP", "RLMD", "ENGN", "TXMD", "ALTO", "GORV", "IMOS", "RPID", "EWTX", "IRWD", "PUBM", "SRRK", "PRLD", "AVDL", "REAL", "TRDA", "SEPN", "MRVI", "ATEX", "KALV", "ELVN", "CNTA", "UK"],
    // "2025-11-15": ["MRSN", "TXMD", "GTBP", "SONN", "RLMD", "IMOS", "UK", "RPID", "SRRK", "CMBM", "IRWD", "SEPN", "ALTO", "AVDL", "EWTX", "ATEX", "ONDS", "RIGL", "CNTA", "CELC", "BCAB", "HROW", "QRHC", "STOK", "OMER"],
    // "2025-11-16": ["MRSN", "GTBP", "SONN", "CMBM", "AVDL", "IMOS", "ATEX", "CNTA", "UK", "SRRK", "TXMD", "SEPN", "ONDS", "RLMD", "KALV", "CLBT", "CELC", "BCAB", "OMER", "DNTH", "SMTK", "CTKB", "QTRX", "TRDA", "MRVI"],
    "2025-11-17": ["BCAB", "SSP", "SGML", "OMER", "ZYME", "JBIO", "RPTX", "DRIO", "CDZI", "JAZZ", "TERN", "ALXO", "UK", "AVDL", "SRRK", "SONN", "ANNX", "FULC", "ALGS", "QRHC", "AMLX", "CTKB", "AIRG", "KALV", "NUVL"],
    "2025-11-18": ["OLMA", "BCAB", "SSP", "CDZI", "SGML", "TERN", "KLRS", "JAZZ", "RPTX", "ONDS", "SRRK", "ALGS", "JBIO", "ALXO", "NAUT", "ARVN", "WALD", "OMER", "ALMS", "ZYME", "ANNX", "UK", "VNDA", "AVDL", "DRIO"],
    "2025-11-19": ["OLMA", "SGML", "BCAB", "ANNX", "SSP", "NAUT", "FULC", "KLRS", "ALGS", "CDZI", "TERN", "SRRK", "JAZZ", "WALD", "EXAS", "ALMS", "DRIO", "JBIO", "RPTX", "ONDS", "ZYME", "AVDL", "UK", "OMER", "DMAC"],
    "2025-11-20": ["SQQQ", "OLMA", "SGML", "BCAB", "ANNX", "EXAS", "AIRG", "ALMS", "DRIO", "ALGS", "TYRA", "NFE", "KLRS", "WALD", "ZYME", "SSP", "CLLS", "CRNC", "DMAC", "TXMD", "GRI", "FULC", "TERN", "RPTX", "CRVO"],
    "2025-11-21": ["SQQQ", "OLMA", "WALD", "ANNX", "EXAS", "NNOX", "PACB", "ALGS", "TYRA", "ADPT", "ALMS", "CRNC", "NRIX", "PSNL", "FULC", "ZYXI", "DMAC", "KLRS", "FOSL", "QCLS", "ZJK", "SGML", "NAUT", "JYD", "TNGX"],
    // "2025-11-22": ["SQQQ", "EXAS", "WALD", "NNOX", "ANNX", "PACB", "ZYXI", "CRNC", "TYRA", "ADPT", "QCLS", "SGML", "FOSL", "NRIX", "ZJK", "ALGS", "PSNL", "TNGX", "JYD", "GRI", "KLRS", "REFR", "LQDT", "ALMS", "OABI"],
    // "2025-11-23": ["SQQQ", "EXAS", "ZYXI", "WALD", "CRNC", "PACB", "ADPT", "TYRA", "ZJK", "NNOX", "NRIX", "FOSL", "JYD", "FEMY", "PSNL", "TNGX", "LQDT", "ANNX", "QCLS", "QTRX", "AZTA", "TXG", "TXMD", "LOBO", "INV"],
    "2025-11-24": ["ZJK", "CGEM", "ZYXI", "BLFY", "ENLV", "PACB", "TYRA", "INV", "ADPT", "LYEL", "JYD", "RLAY", "QDEL", "TXG", "GRAL", "WALD", "TNGX", "SEPN", "BCAX", "OLMA", "AZTA", "PSNL", "GRI", "JACK", "LPRO"],
    "2025-11-25": ["ZJK", "INV", "BLFY", "ZYXI", "PACB", "JYD", "CGEM", "SYM", "ENLV", "PSNL", "TLSI", "JACK", "QDEL", "TYRA", "ADPT", "SPRY", "FOSL", "SMX", "HCAT", "ESPR", "LYEL", "CSTE", "CRMT", "TITN", "NNOX"],
    "2025-11-26": ['SMX', 'ZYXI', 'AMBR', 'ZJK', 'QNTM', 'SYM', 'CSTE', 'BLFY', 'INV', 'ARWR', 'KALA', 'CGEM', 'IBG', 'LYEL', 'TLSI', 'ESPR', 'HCAT', 'OLMA', 'CTXR', 'JACK', 'PACB', 'JYD', 'SPRY', 'FOSL', 'TYRA'],
    // "2025-11-27": ["SMX", "ZYXI", "AMBR", "ZJK", "QNTM", "SYM", "CSTE", "BLFY", "INV", "ARWR", "KALA", "CGEM", "LYEL", "TLSI", "ESPR", "IBG", "HCAT", "OLMA", "CTXR", "SPRY", "FOSL", "JYD", "JACK", "PACB", "TYRA"]
};
const TOPS_2 = {
    '2025-09-26': ['IBG', 'SLNH', 'CLPT', 'MFH', 'GDEV', 'KOD', 'ALXO', 'DRIO', 'FLNC', 'HOWL', 'CTMX', 'FLUX', 'QURE', 'INDP', 'SKYT', 'SAVA', 'NBTX', 'ODP', 'TKNO', 'KLRS', 'RAPT', 'ANNX', 'CRNX', 'RGTI', 'VERI'],
    '2025-09-29': ['LESL', 'IBG', 'ENTA', 'DWTX', 'DRIO', 'FLUX', 'CTMX', 'TLRY', 'QURE', 'MFH', 'MRUS', 'ALXO', 'PRLD', 'CLPT', 'KLRS', 'BRNS', 'GDEV', 'SGMO', 'STKS', 'GRAL', 'CDLX', 'CRBU', 'CRNX', 'NBTX', 'GRWG'],
    '2025-09-30': ['LESL', 'IBG', 'ENTA', 'MFH', 'DRIO', 'DWTX', 'PRLD', 'TLRY', 'MRUS', 'GDEV', 'ANAB', 'CTMX', 'DPRO', 'GRAL', 'SKYT', 'NBTX', 'KLRS', 'BCAX', 'FATE', 'KRRO', 'APPS', 'STKS', 'RLMD', 'ADSE', 'MNMD'],
    '2025-10-01': ['LESL', 'IBG', 'ENTA', 'DRIO', 'MFH', 'DWTX', 'DPRO', 'PRLD', 'GDEV', 'ANAB', 'CTMX', 'MRUS', 'TORO', 'TLRY', 'GRAL', 'KLRS', 'OLMA', 'SKYT', 'SMCX', 'BCAX', 'VTYX', 'BRNS', 'PLUG', 'RLMD', 'ABCL'],
    '2025-10-02': ['LESL', 'IBG', 'ENTA', 'DRIO', 'GDEV', 'MFH', 'DPRO', 'RLMD', 'KLRS', 'DWTX', 'PRLD', 'MRUS', 'GRAL', 'ANAB', 'CTMX', 'TORO', 'SKYT', 'ABSI', 'NBTX', 'OLMA', 'TLRY', 'SMCX', 'BCAX', 'INOD', 'ONDS'],
    '2025-10-03': ['LESL', 'MFH', 'ENTA', 'GDEV', 'FEMY', 'DPRO', 'PLUG', 'NEUP', 'DWTX', 'CLPT', 'RLMD', 'MRUS', 'KLRS', 'ANAB', 'BCAX', 'TLRY', 'PRLD', 'DRIO', 'NBTX', 'LYEL', 'GRAL', 'ASTS', 'IBG', 'ERAS', 'OLMA'],
    '2025-10-06': ['FEMY', 'PLUG', 'SMTK', 'AMDL', 'NEUP', 'CRML', 'MFH', 'BLNK', 'SLDP', 'KOPN', 'HUMA', 'BZAI', 'NVX', 'RGTI', 'ARQQ', 'KLRS', 'FLNC', 'NNE', 'ONDS', 'TORO', 'HIVE', 'FCEL', 'BLDP', 'RCAT', 'ASTS'],
    '2025-10-07': ['FEMY', 'MFH', 'SLDP', 'AMDL', 'NVX', 'VELO', 'BZAI', 'HIVE', 'SMTK', 'CRML', 'EGAN', 'RGTI', 'ONDS', 'NNE', 'PLUG', 'RCAT', 'NEUP', 'KOPN', 'BLNK', 'ARQQ', 'AMTX', 'TMC', 'FLUX', 'CMMB', 'AMD'],
    '2025-10-08': ['FEMY', 'AMDL', 'CRML', 'MFH', 'SLDP', 'VELO', 'GTBP', 'NVX', 'HIVE', 'BZAI', 'FLUX', 'POET', 'SMTK', 'QTTB', 'ONDS', 'AMD', 'EGAN', 'CLPT', 'BCAB', 'KOPN', 'RGTI', 'ASTS', 'RNAZ', 'NEUP', 'RCAT'],
    '2025-10-09': ['FEMY', 'CRML', 'AMDL', 'NVX', 'MFH', 'HIVE', 'SLDP', 'SMTK', 'BCAB', 'QTTB', 'FLUX', 'LAES', 'RGTI', 'BZAI', 'ASTS', 'LWLG', 'ZSPC', 'VELO', 'SERV', 'NBTX', 'DPRO', 'POET', 'AMD', 'EGAN', 'CLPT'],
    '2025-10-10': ['NVX', 'CRML', 'FEMY', 'QTTB', 'AMDL', 'HIVE', 'FLUX', 'SLDP', 'EGAN', 'BCAB', 'PTGX', 'RNAZ', 'FATE', 'BZAI', 'ATYR', 'APGE', 'GLUE', 'LAES', 'AMD', 'APLD', 'METC', 'TNYA', 'NYXH', 'ORKA', 'ASTS'],
    '2025-10-13': ['CRML', 'OP', 'NVX', 'LAES', 'GLUE', 'LGO', 'APGE', 'ZSPC', 'QTTB', 'IMAB', 'CIFR', 'NVTS', 'APLD', 'METC', 'EOSE', 'RGTI', 'ORKA', 'PTGX', 'DPRO', 'MRSN', 'SAVA', 'CGEM', 'SYRE', 'GGAL', 'QSI'],
    '2025-10-14': ['CRML', 'LAES', 'NVTS', 'SMTK', 'ATXS', 'VELO', 'NVX', 'OP', 'GLUE', 'RGTI', 'LGO', 'FLNC', 'APLD', 'QTTB', 'RCKT', 'METC', 'INDI', 'ORKA', 'ASPI', 'QSI', 'SYRE', 'IMAB', 'CRBP', 'PTGX', 'WULF'],
    '2025-10-15': ['CRML', 'NVTS', 'LAES', 'VERI', 'FLNC', 'QSI', 'ATXS', 'FOSL', 'GLUE', 'SMTK', 'VELO', 'OP', 'BIOX', 'APLD', 'BTDR', 'IBG', 'SANA', 'IRBT', 'CGEM', 'INDI', 'RGTI', 'CRBP', 'SYRE', 'NVX', 'RCKT'],
    '2025-10-16': ['PRAX', 'NVTS', 'CRML', 'LAES', 'ATXS', 'QSI', 'WHWK', 'OP', 'CRBP', 'LOBO', 'FLNC', 'BTDR', 'GLUE', 'CGEM', 'APLD', 'SBFM', 'BIOX', 'IMAB', 'VERI', 'FEMY', 'SYRE', 'VELO', 'IBG', 'SMTK', 'INDI'],
    '2025-10-17': ['PRAX', 'NVTS', 'CRML', 'KZR', 'ATXS', 'LOBO', 'QSI', 'SBFM', 'FLNC', 'WHWK', 'IRON', 'VERI', 'IBG', 'INDI', 'BIOX', 'CRBP', 'BTDR', 'IMAB', 'SLNH', 'OP', 'RANI', 'GLUE', 'PTGX', 'SANA', 'SLN'],
    '2025-10-20': ['PRAX', 'GSIT', 'REPL', 'RANI', 'WHWK', 'CELC', 'KZR', 'CTXR', 'RAPT', 'GRAL', 'SLNH', 'NVTS', 'SANA', 'LOBO', 'STRO', 'PSNL', 'AVTX', 'PACB', 'SLN', 'ABSI', 'BEAM', 'XNCR', 'JBHT', 'IRON', 'RLAY'],
    '2025-10-21': ['NERV', 'GSIT', 'REPL', 'RANI', 'BYND', 'KZR', 'CELC', 'RAPT', 'IBIO', 'STRO', 'NAUT', 'KOD', 'AVTX', 'FEMY', 'PRAX', 'PLRX', 'SVRA', 'AVDL', 'REAL', 'MGNX', 'CLOV', 'BLTE', 'SLN', 'FLWS', 'VICR'],
    '2025-10-22': ['NERV', 'GSIT', 'BYND', 'REPL', 'RANI', 'YYAI', 'IBIO', 'CELC', 'VICR', 'KZR', 'NDLS', 'STRO', 'RAPT', 'AVDL', 'KOD', 'ISRG', 'LXEH', 'PRAX', 'IHRT', 'SABR', 'NAUT', 'PLRX', 'HCSG', 'FLWS', 'TXMD'],
    '2025-10-23': ['NERV', 'SCNX', 'GSIT', 'BYND', 'REPL', 'VTYX', 'RANI', 'IBIO', 'VICR', 'CELC', 'LXEH', 'KZR', 'NDLS', 'NAUT', 'BIOA', 'AVTX', 'ISRG', 'FLWS', 'RAPT', 'TXMD', 'RXT', 'PI', 'AVDL', 'IHRT', 'IVA'],
    '2025-10-24': ['NERV', 'GSIT', 'REPL', 'BYND', 'SCNX', 'VTYX', 'RANI', 'IBIO', 'VICR', 'CELC', 'CLOV', 'MOFG', 'LXEH', 'BIOA', 'NDLS', 'SNDK', 'KOD', 'CTXR', 'FLWS', 'AVTX', 'ISRG', 'AVDL', 'NAUT', 'IHRT', 'IVA'],
    '2025-10-27': ['VTYX', 'SCNX', 'GGAL', 'DYN', 'IBIO', 'LXEH', 'RNA', 'BIOA', 'MOFG', 'IVA', 'ETHZ', 'SONN', 'GLUE', 'VERI', 'AXTI', 'PI', 'GSIT', 'LAES', 'SNDK', 'AMDL', 'OKUR', 'CLOV', 'CELC', 'OUST', 'LITE'],
    '2025-10-28': ['GGAL', 'SCNX', 'DYN', 'RNA', 'MOFG', 'AXTI', 'GLUE', 'ETHZ', 'AMDL', 'LITE', 'WULF', 'AGYS', 'REPL', 'CLOV', 'MBX', 'SNDK', 'UROY', 'NVDL', 'NVDU', 'VERI', 'PI', 'GTX', 'RLMD', 'INBX', 'NAUT'],
    '2025-10-29': ['GGAL', 'SCNX', 'DYN', 'RNA', 'AXTI', 'SNDK', 'ACDC', 'LITE', 'INBX', 'MBX', 'GLUE', 'AMDL', 'MOFG', 'ZEUS', 'FLNC', 'CMBM', 'NVDL', 'NVDU', 'TER', 'AXGN', 'JAMF', 'STX', 'REPL', 'POWL', 'PI'],
    '2025-10-30': ['CMBM', 'GGAL', 'HBIO', 'DYN', 'RNA', 'AXTI', 'FORM', 'MBX', 'GH', 'GLUE', 'SNDK', 'INBX', 'ACDC', 'MOFG', 'IMVT', 'SCNX', 'FLNC', 'VIAV', 'BIRD', 'TER', 'AXGN', 'LITE', 'ZEUS', 'JAMF', 'EWTX'],
    '2025-10-31': ['ACDC', 'ATEC', 'AXGN', 'AXTI', 'BIRD', 'CHRW', 'CMBM', 'CSIQ', 'EWTX', 'FORM', 'GH', 'HBIO', 'IBIO', 'IMVT', 'INBX', 'JAMF', 'MBX', 'MNOV', 'RANI', 'TER', 'TVTX', 'UROY', 'VIAV', 'VTYX', 'ZEUS'],
    '2025-11-03': ['ALAB', 'AMKR', 'ATEC', 'AXTI', 'BIRD', 'BLTE', 'CIFR', 'CSIQ', 'CTMX', 'HUT', 'ILMN', 'IREN', 'IRWD', 'NAUT', 'PACB', 'PRLD', 'RANI', 'SLNH', 'TALK', 'TERN', 'TTMI', 'TVTX', 'VTYX', 'WDC', 'ZBIO'],
    '2025-11-04': ['ATEC', 'AUPH', 'AXTI', 'BLTE', 'CIFR', 'CSIQ', 'CSTL', 'CTMX', 'EVER', 'FEMY', 'IHRT', 'IREN', 'IRWD', 'LQDA', 'LWLG', 'NAUT', 'PRLD', 'RANI', 'RLMD', 'SANM', 'TALK', 'TCMD', 'TERN', 'TVTX', 'XMTR'],
    '2025-11-05': ['ATEC', 'AUPH', 'AXTI', 'BDSX', 'CIFR', 'CSIQ', 'CSTL', 'CTMX', 'DAWN', 'EVER', 'FEMY', 'GRNQ', 'IHRT', 'INV', 'IREN', 'IRWD', 'RANI', 'SANM', 'SLDP', 'TALK', 'TCMD', 'TERN', 'VCYT', 'VTYX', 'XMTR'],
    '2025-11-06': ['ALTO', 'APPN', 'BHF', 'CSIQ', 'CSTL', 'CTMX', 'DAWN', 'EVER', 'FEMY', 'GRNQ', 'IHRT', 'INV', 'INVA', 'IRWD', 'LITE', 'MBX', 'RANI', 'RLMD', 'SANM', 'SBGI', 'SITM', 'TCMD', 'TERN', 'VCYT', 'XMTR'],
    '2025-11-07': ['ABL', 'ALTO', 'APPN', 'APYX', 'BHF', 'COLL', 'CSIQ', 'CSTL', 'DAWN', 'ESTA', 'EVER', 'FEMY', 'IHRT', 'INV', 'LITE', 'MBX', 'NATR', 'OS', 'RLMD', 'SANM', 'SBGI', 'TCMD', 'TERN', 'VCYT', 'XMTR'],
    '2025-11-10': ['ABL', 'APPN', 'APYX', 'ARVN', 'ATNI', 'CSIQ', 'DSGN', 'EOSE', 'FEMY', 'FNKO', 'INV', 'IRWD', 'LFST', 'MTSI', 'NATR', 'NRDS', 'ORGO', 'OS', 'PANL', 'PLCE', 'PLUS', 'RDNW', 'SKYT', 'SNDK', 'TXG'],
    '2025-11-11': ['ABL', 'APPN', 'APYX', 'ATNI', 'CMPX', 'DSGN', 'EOSE', 'EWTX', 'IRWD', 'LFST', 'LUNG', 'NATR', 'NRDS', 'ORGO', 'PANL', 'PLUS', 'PUBM', 'RDNW', 'RPID', 'SKYT', 'SNDK', 'TBPH', 'TXG', 'TXMD', 'VELO'],
    '2025-11-12': ['ABL', 'ALTO', 'APPN', 'APYX', 'ATNI', 'BDTX', 'CMBM', 'CMPX', 'EWTX', 'GSAT', 'IRWD', 'KALV', 'LFST', 'NATR', 'NRDS', 'ORGO', 'PANL', 'PLUS', 'RDNW', 'RLMD', 'RPID', 'SNDK', 'TSEM', 'TXG', 'TXMD'],
    '2025-11-13': ['ALTO', 'APYX', 'AXTI', 'EWTX', 'FLGT', 'GSAT', 'IMOS', 'IRWD', 'LVLU', 'MLTX', 'MRSN', 'NATR', 'NAUT', 'ORGO', 'PANL', 'PLUS', 'RDNW', 'RLMD', 'RPID', 'SONN', 'SSP', 'TBPH', 'TRDA', 'TSEM', 'TXMD'],
    '2025-11-14': ['ALTO', 'AVDL', 'CELC', 'CTKB', 'DSP', 'EWTX', 'GSAT', 'GTBP', 'HBIO', 'IMOS', 'IRWD', 'KALV', 'MLTX', 'MRSN', 'PRLD', 'RIGL', 'RLMD', 'RPID', 'SEPN', 'SONN', 'SRRK', 'SSP', 'TERN', 'TRDA', 'TXMD',],
    '2025-11-17': ['ALXO', 'AVDL', 'BCAB', 'CLLS', 'CRVO', 'CRVS', 'CTKB', 'FULC', 'HBIO', 'INV', 'JAZZ', 'JBIO', 'KALV', 'KLRS', 'PGNY', 'PRLD', 'QRHC', 'SEPN', 'SGML', 'SONN', 'SRRK', 'SSP', 'TERN', 'WALD', 'ZYME',],
    '2025-11-18': ['ALGS', 'ALMS', 'ALXO', 'ARVN', 'AVDL', 'BCAB', 'CTKB', 'EYPT', 'FULC', 'JAZZ', 'JBIO', 'KLRS', 'NAUT', 'OLMA', 'ONDS', 'RIGL', 'SEPN', 'SGML', 'SRRK', 'SSP', 'STOK', 'TERN', 'VNDA', 'WALD', 'ZYME',],
    '2025-11-19': ['ALGS', 'ALMS', 'ANNX', 'AVDL', 'BCAB', 'CLLS', 'CRVO', 'EXAS', 'EYPT', 'FULC', 'JAZZ', 'JBIO', 'KLRS', 'NAUT', 'NRIX', 'OLMA', 'ONDS', 'SEPN', 'SGML', 'SRRK', 'SSP', 'TERN', 'VNDA', 'WALD', 'ZYME',],
    '2025-11-20': ['ABVX', 'ALGS', 'ALMS', 'ANNX', 'BCAB', 'CLLS', 'CRVO', 'EXAS', 'FULC', 'GRNQ', 'JAZZ', 'JBIO', 'KLRS', 'NRIX', 'OLMA', 'RLMD', 'SEPN', 'SGML', 'SQQQ', 'SSP', 'TERN', 'TXMD', 'TYRA', 'WALD', 'ZYME',],
    '2025-11-21': ['ADPT', 'ALGS', 'ALMS', 'ANNX', 'ARQT', 'BCAX', 'CBLL', 'DMAC', 'EXAS', 'FULC', 'INV', 'KLRS', 'NAUT', 'NNOX', 'NRIX', 'OLMA', 'PACB', 'PSNL', 'QCLS', 'SGML', 'SQQQ', 'TNGX', 'TYRA', 'WALD', 'ZJK',],
    '2025-11-24': ['ADPT', 'AZTA', 'BCAX', 'CGEM', 'GRAL', 'GRI', 'INV', 'JYD', 'LPRO', 'LYEL', 'OLMA', 'PACB', 'PSNL', 'QDEL', 'QTRX', 'RLAY', 'SEPN', 'TENX', 'TLSI', 'TNGX', 'TXG', 'TYRA', 'WALD', 'WGS', 'ZJK',],
    '2025-11-25': [
        'ADPT', 'AZTA', 'CBLL', 'CGEM', 'CSTE', 'ESPR', 'FOSL', 'INV', 'JACK', 'JYD', 'LYEL', 'NNOX', 'OLMA', 'PACB', 'PSNL', 'QDEL', 'RLAY', 'SMX', 'SPRY', 'TENX', 'TITN', 'TLSI', 'TNGX', 'TYRA', 'ZJK',
        //* AT 10:45 AM EST
        // 'ADPT','ARWR','CGEM','CSTE','CTXR','ESPR','FOSL','IBG','INV','JACK','JYD','LYEL','OLMA','PACB','PSNL','QDEL','SMX','SNBR','SPRY','TLSI','TNGX','TYRA','URBN','ZJK','ZYXI'
    ],
    '2025-11-26': ['ADPT', 'AZTA', 'CBLL', 'CGEM', 'CSTE', 'ESPR', 'FOSL', 'INV', 'JACK', 'JYD', 'LYEL', 'NNOX', 'OLMA', 'PACB', 'PSNL', 'QDEL', 'RLAY', 'SMX', 'SPRY', 'TENX', 'TITN', 'TLSI', 'TNGX', 'TYRA', 'ZJK',],
};
const CONFIG = {
    algo_name: 'algo', // algo | algo1 | algo2 | algo3 | algo4
    algo: {
        crypto: 'X2',

        // stocks: 'X',
        // stop_pct: 1.0,

        stocks: 'W',
        stop_pct: 0.9,

        // get_reset_window: (t) => { return new Date(t).getDay() === 5; },
        // get_reset_window: (t) => { return getYMD(getLastFridayOfMonth(new Date(t).getFullYear(), new Date(t).getMonth())); },
        get_reset_window: (t) => { return getWeekName(new Date(t)); },
        // get_reset_window: (t) => { return getMonthName(new Date(t)); },
        // get_reset_window: (t) => { return getQuarterName(new Date(t)); },
        // get_reset_window: (t) => { return getYMD(new Date(t)); },

        //* BAR CHART WINDOW SIZE
        summary_window: 'months', //* days | weeks | months | quarters

        //* USE SETTING TO NORMALIZE INFO PAGE DATA TO THE SAME INVESTMENT
        // seed: 10,

        //* START OF DAY SELL, BUY WILL OCCUR ON SAME DAY BASED ON ALGO LOGIC
        // sell_dates: ['2025-11-27'],
        // // sell_dates: [/*'2025-11-11',*/ '2025-11-13', '2025-11-14', '2025-11-17', '2025-11-18'],
        // // start: new Date(`2024-12-15T00:00:00`),

        start: new Date(`2024-12-15T00:00:00`),
        // start: new Date(`2024-12-15T00:00:00`),
        // end: new Date(`2025-11-02T23:59:59`),
        // end: new Date(`${getYMD(new Date())}T23:59:59`),
        // timeframe: '1D',
    },
    algo1: { /* STANDARD */
        crypto: 'X',
        stocks: 'F',
        // get_reset_window: (t) => { return getWeekName(new Date(t)); },
        get_reset_window: (t) => { return getMonthName(new Date(t)); },
        summary_window: 'months', // days | weeks | months | quarters
    },
    algo2: { /* WEEKS */
        crypto: 'F',
        stocks: 'Z',
        get_reset_window: (t) => { return getWeekName(new Date(t)); },
        summary_window: 'months', // days | weeks | months | quarters
    },
    algo3: { /* MONTHS */
        crypto: 'F',
        stocks: 'X',
        get_reset_window: (t) => { return getMonthName(new Date(t)); },
        summary_window: 'months', // days | weeks | months | quarters
    },
    algo4: { /* BUY AND HOLD w/ STOP_LOSS && MONTH RESET */
        crypto: 'X',
        stocks: 'X',
        stop_pct: 0.95,
        get_reset_window: (t) => { return getMonthName(new Date(t)); },
        summary_window: 'months', // days | weeks | months | quarters
    },
    algo5: { /* BUY AND HOLD w/ QUARTER RESET */
        crypto: 'X',
        stocks: 'X',
        // stop_pct: 0.95,
        get_reset_window: (t) => { return getQuarterName(new Date(t)); },
        summary_window: 'months', // days | weeks | months | quarters
    },
    algo6: { /* STANDARD */
        crypto: 'X',
        stocks: 'F',
        get_reset_window: (t) => { return getWeekName(new Date(t)); },
        // get_reset_window: (t) => { return (new Date(t).getDate() <= 15).toString(); },
        summary_window: 'weeks', // days | weeks | months | quarters
    },
    // initial_seed: 1000, // per symbol
    symbol_groups: [
        // {
        //     name: 'DAY TRADES',
        //     include: true,
        //     // symbols: [
        //     //     ...TOPS['2025-11-26'],
        //     // ]//.sort(),
        //     symbols: [
        //         "MFH",
        //         "DRIO",
        //         "OPEN",
        //         "KLRS",
        //         "ONDS",
        //         "VERI",
        //         "LXEH",
        //         "SLNH",
        //         "PRLD",
        //         "CRML",
        //         "ALXO",
        //         "TLRY",
        //         "AXTI",
        //         "GLUE",
        //         "RGTI",
        //         "IBG",
        //         "SONN",
        //         "RLMD",
        //         "FLNC",
        //         "SMTK",
        //         "DUO",
        //         "BCAB",
        //         "FEMY",
        //         "RANI",
        //         "ABTC"
        //     ]
        // },
        {
            name: 'TOP 10',
            include: true,
            // seed: 5,
            symbols: [
                ...FILTER.sort(),
                // 'MA',
                // ...('KTOS,GH,ANAB,ADPT,ATEC,AVTX,AUPH,OCUL,NRIX,NAUT,NEO,DLTR,DHC,DOOO,DNUT,DSP,NDAQ,FGM,JTEK'.split(',')).sort()

            ].filter((v) => !['PLTR', 'SOFI', 'HOOD', 'CRDO',].includes(v)).sort(),
        },
        {
            //# R & D
            name: 'R & D', //@ TOP SCORES
            // seed: 10,
            include: true,
            symbols: [
                // 'IXUS','TQQQ','VXUS','VUG','VTV','VOO','VTI','SPY','QQQ','DIA',
                ...scores
                    .filter((v) => v.score >= 4 && v.pct > 50)
                    .sort((a, b) => b.pct > a.pct ? 1 : -1)
                    .map((v) => v.symbol)
                    .slice(0, 19)
                    .filter((v) => !['RGTI', 'INDV', 'TTMI', 'PRCH',].includes(v))
                    .filter((v) => !FILTER.includes(v))
                    .sort(),
                // .filter((v) => !['APP', 'RGTI', 'EYE', 'GILT',].includes(v)),

                //* MAG 7
                // ...['GOOG','AMZN','AAPL','META','MSFT','NVDA','TSLA',].sort(),

                // * CRYPTO
                // 'AVAX/USD', 'BCH/USD', 'BTC/USD', 'DOGE/USD', 'ETH/USD', 'XRP/USD', 'SUSHI/USD',
            ]//.sort()
        },
        {
            //# STOCKS - MANUALLY CURATED
            name: 'STOCKS',
            include: true,
            // seed: 30,
            symbols: [
                ...['RING', 'IREN', 'CIFR', 'HUT', 'TMC', /*'DDOG',*/ 'GE', 'GEV', /*'IBM',*/ /*'NFLX',*/ 'OKLO', 'PSIX',
                    'HOOD', /*'FGM',*/ 'AMD', 'AVGO', 'COIN', 'LEU', 'OPEN',
                    'QUBT', 'RKLB', 'SMCI', 'SNDK', 'SNOW', /*'TPB',*/ 'TSEM', 'UUUU', 'SHOP', //'VIXY',
                    'APH', /*'VTR',*/ 'LLY', 'GOOGL',].filter((v) => !FILTER.includes(v)),
                'PLTR', 'SOFI', 'HOOD', 'CRDO', 'INDV', 'TTMI',

                // 'SNDK' //# testing

                // 'RING', 'IREN', 'CIFR', 'HUT', 'TMC', 'DDOG', 'GE', 'GEV', 'OKLO', 'PSIX',
                // 'HOOD', 'AMD', 'AVGO', 'COIN', 'LEU', 'OPEN',
                // 'QUBT', 'RKLB', 'SMCI', 'SNDK', 'SNOW', 'TPB', 'TSEM', 'UUUU', 'SHOP', 'APH', 
                // // 'VIXY',
                // // 'VTR', 'LLY', 'FGM', 'NFLX', 'IBM',  //# REMOVED: TOO LITTLE APY
                // // 'SNDK' //# testing
            ].sort(),
        },
        // {
        //     //# STOCKS - MANUALLY CURATED
        // {
        //     name: 'TOP',
        //     include: true,
        //     seed: 10,
        //     symbols: [
        //         // 'HOOD','GE','PLTR','LEU','OKLO',
        //         'PLTR', 'KOPN', 'RKLB', 'SHOP','GSIB',
        //     ].sort(),
        // },
        // { name: 'TOP_SCORES', include: false, symbols: scores.filter((v) => v.score >= 4).map((v) => v.symbol).sort() },
        // { name: 'ETF', symbols: ['ONEQ', 'AVDV', 'SPY', 'VOO', 'VTI', /*'IVES', NEEDS START DATE*/ ].sort() },
        // { name: 'TECH', symbols: [
        //     'AAPL', 'MSFT', 'GOOGL', 'AMZN', 'FB', 'TSLA', 'NVDA', /*'ADBE',*/ 'INTC', 'CSCO', //# TECH
        //     'NVDA', 'AMD', 'INTC', /*'TXN',*/ 'QCOM', 'AVGO', 'MU', 'ASML', /*'LRCX',*/ 'KLAC', //# SEMICONDUCTORS
        // ].sort() },
        // { name: 'FOOD & BEV', symbols: ['KO', 'PEP', 'MCD', 'SBUX', 'CMG', 'YUM', 'MDLZ', 'GIS', 'KHC', 'TSN'].sort() },
        //# TOP 90
        // {
        //     name: 'TOP 90 d',
        //     include: true,
        //     // seed: 15,
        //     symbols: [
        //         'FLUX',
        //         'TNYA', 'FOSL', 'GEOS', 'GSIB', 'IBG', 'MFH',
        //         'PLUG', 'NBTX', 'NTLA', 'MU', 'CAMT',
        //         'BLNK', 'AXTI', 'BTDR', 'BTSG', 'CVRX',//'CTXR',
        //         'GLUE',//'FTRE',

        //         //# ALL
        //         // 'RING', 'IREN', 'CIFR', 'HUT', 'TMC', 'DDOG', 'GE', 'GEV', 'IBM', 'NFLX', 'OKLO', 'PSIX',
        //         // 'HOOD', 'FGM', 'AMD', 'AVGO', 'COIN', 'LEU', 'NIO', 'OPEN',
        //         // 'QUBT', 'RKLB', 'SMCI', 'SNDK', 'SNOW', 'TPB', 'TSEM', 'UUUU','SHOP', //'VIXY',

        //         // ...scores
        //         //     .filter((v) => v.score >= 4 && v.pct > 50)
        //         //     .sort((a, b) => b.pct > a.pct ? 1 : -1)
        //         //     .map((v) => v.symbol)
        //         //     .slice(0, 19)
        //         //     .filter((v) => !['RGTI',].includes(v)),


        //     ].sort()
        // },
        {
            name: 'CRYPTO',
            include: false,
            symbols: [
                // 'AAPL',
                'AVAX/USD', 'BCH/USD', 'BTC/USD', 'DOGE/USD', 'ETH/USD', 'XRP/USD', 'SUSHI/USD',

                // 'BAT/USD', 'PEPE/USD', 'XTC/USD', 'DOT/USD',  
                // 'TRUMP/USD', /* 'SHIB/USD', */ /* 'YFI/USD', */ 'SUSHI/USD',
                // 'AVAX/USD', 

                // 'BCH/USD', 'BTC/USD', 'DOGE/USD', 'ETH/USD', /* 'XRP/USD', */

                // 'GRT/USD', 'SOL/USD', 'UNI/USD',
            ].sort()
        },
        { name: 'AERO', symbols: ['BA', 'LMT', 'NOC', 'RTX', 'GD', 'HII', 'TXT', 'CW', 'AJRD', 'HEI'].sort() },
        { name: 'AIRLINES', symbols: ['AAL', 'DAL', 'UAL', 'LUV', 'ALK', 'JBLU', 'SAVE', 'CPA', 'FFT', 'HA'].sort() },
        { name: 'AUTOS', symbols: ['F', 'GM', 'HMC', 'TM', 'NIO', 'LI', 'RIVN', 'XPEV', 'LCID'].sort() },
        { name: 'BANKS', symbols: ['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'AXP', 'BK', 'PNC', 'USB'].sort() },
        { name: 'CANNABIS', symbols: ['CGC', 'CRON', 'TLRY', 'APHA', 'NCBD', 'ACB', 'SLNG', 'VFF', 'HEXO', 'MJ'].sort() },
        { name: 'CLEAN ENERGY', symbols: ['TSLA', 'NEE', 'ENPH', 'SEDG', 'FSLR', 'BE', 'RUN', 'SPWR', 'PLUG', 'BLDP'].sort() },
        { name: 'ENERGY', symbols: ['XOM', 'CVX', 'COP', 'SLB', 'EOG', 'PSX', 'VLO', 'MPC', 'KMI', 'OXY'].sort() },
        { name: 'ETF', symbols: ['SPY', 'QQQ', 'DIA', 'IWM', 'VTI', 'VOO', 'EEM', 'GLD', 'SLV', 'TLT'].sort() },
        { name: 'FINANCE', symbols: ['JPM', 'BAC', 'WFC', 'C', 'GS', 'MS', 'AXP', 'BK', 'PNC', 'USB'].sort() },
        { name: 'FOOD & BEV', symbols: ['KO', 'PEP', 'MCD', 'SBUX', 'CMG', 'YUM', 'MDLZ', 'GIS', 'KHC', 'TSN'].sort() },
        { name: 'GAMING', symbols: ['ATVI', 'EA', 'TTWO', 'ZNGA', 'UBSFY', 'NCVAF', 'CDR', 'GME', 'PLTK', 'RBLX'].sort() },
        { name: 'HEALTHCARE', symbols: ['JNJ', 'PFE', 'MRK', 'ABBV', 'TMO', 'UNH', 'MDT', 'BMY', 'AMGN', 'GILD'].sort() },
        { name: 'HOTELS', symbols: ['MAR', 'HLT', 'HST', 'WYNN', 'NCLH', 'CCL', 'RCL', 'IHG', 'EXPE', 'BKNG'].sort() },
        { name: 'INDUSTRIALS', symbols: ['BA', 'CAT', 'DE', 'GE', 'LMT', 'MMM', 'UTX', 'HON', 'FDX', 'UPS'].sort() },
        { name: 'INSURANCE', symbols: ['AIG', 'ALL', 'MET', 'PRU', 'TRV', 'HIG', 'CINF', 'PGR', 'WRB', 'L'].sort() },
        { name: 'MATERIALS', symbols: ['LIN', 'APD', 'ECL', 'SHW', 'DD', 'NEM', 'FCX', 'MLM', 'VMC', 'PPG'].sort() },
        { name: 'MEDIA', symbols: ['DIS', 'NFLX', 'CMCSA', 'CHTR', 'VIAC', 'T', 'VZ', 'ATVI', 'EA', 'TTWO'].sort() },
        { name: 'MISC', symbols: ['DIS', 'NFLX', 'PYPL', 'SQ', 'ZM', 'UBER', 'LYFT', 'TWTR', 'SNAP', 'SHOP'].sort() },
        { name: 'PHARMA', symbols: ['PFE', 'MRK', 'ABBV', 'BMY', 'AMGN', 'GILD', 'LLY', 'AZN', 'JNJ', 'RHHBY'].sort() },
        { name: 'PHOTOVOLTAIC', symbols: ['ENPH', 'SEDG', 'FSLR', 'SPWR', 'RUN', 'CSIQ', 'JKS', 'DQ', 'VSLR', 'SUNE'].sort() },
        { name: 'REAL ESTATE', symbols: ['AMT', 'PLD', 'CCI', 'EQIX', 'PSA', 'SPG', 'DLR', 'O', 'VTR', 'AVB'].sort() },
        { name: 'RETAIL', symbols: ['WMT', 'TGT', 'COST', 'HD', 'LOW', 'M', 'KSS', 'TJX', 'ROST', 'BBY'].sort() },
        { name: 'SEMICONDUCTORS', symbols: ['NVDA', 'AMD', 'INTC', 'TXN', 'QCOM', 'AVGO', 'MU', 'ASML', 'LRCX', 'KLAC'].sort() },
        { name: 'SOCIAL MEDIA', symbols: ['FB', 'TWTR', 'SNAP', 'PINS', 'TTD', 'SPOT', 'UBER', 'LYFT', 'TME', 'BILI'].sort() },
        { name: 'TECH', symbols: ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'FB', 'TSLA', 'NVDA', 'ADBE', 'INTC', 'CSCO'].sort() },
        { name: 'TELECOM', symbols: ['VZ', 'T', 'TMUS', 'S', 'CHTR', 'CMCSA', 'DISH', 'CCI', 'LUMN', 'CTL'].sort() },
        { name: 'TRANSPORT', symbols: ['UPS', 'FDX', 'CHRW', 'JBHT', 'EXPD', 'KEX', 'MATX', 'GWR', 'NSC', 'UNP'].sort() },
        { name: 'UTILITIES', symbols: ['NEE', 'DUK', 'SO', 'AEP', 'EXC', 'D', 'PEG', 'SRE', 'ES', 'XEL'].sort() },
    ],
}